theme/light/src/styles/core/grid/_breakpoints.scss

Mobile breakpoint is now below 1056px instead of 672px
Fixes: Breakpoint change in figma from sm to md for mobile view
Run grid and and sidebar should be removed at 1055px and below

Mobile breakpoint is now below 1056px instead of 672px

---

theme/light/src/styles/core/grid/_grid.scss
theme/light/src/styles/core/grid/_mixins.scss

Add no-padding on the push column
**NOTE** Only added to the push grid now
Compare no-padding and padding
```html
<div class="sdds-container-push">
<div class="sdds-row content">
<div class="no-padding sdds-col-xxlg-9 sdds-col-xlg-9 sdds-col-lg-1 sdds-col-md-1 sdds-col-sm-1">
<div class="outside">
<span class="inside">1</span>
</div>
</div>
<div class="sdds-col-xxlg-9 sdds-col-xlg-9 sdds-col-lg-1 sdds-col-md-1 sdds-col-sm-1">
<div class="outside">
<span class="inside">2</span>
</div>
</div>
</div>
</div>
```

Add no padding mixin to the push grid

---

theme/light/src/styles/core/typography/_tokens.scss
theme/light/src/styles/core/typography/compile.js
theme/light/src/styles/core/typography/package.json

- Add imported files needed for typography from compiler
Run npm run build inside typography.
External file import is included in the package (Base_unit)

Add typography package css & scss

---

components/src/components/dropdown/dropdown-option.tsx
components/src/components/dropdown/dropdown.stories.js
components/src/components/dropdown/dropdown.tsx
components/src/components/dropdown/readme.md
components/src/patterns/dropdown-filter/dropdown-filter.tsx

- When click outside, keep selected value
- Set default option to work
Fixes: #90 [AB#520](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/520)
- Open storybook
- Go to dropdown
- Select one of the option
- Click outside
- See the selected option is still selected
- Previously, selected will lose classes if 2 dropdown exist, and if we click on the other dropdown
- Now it should only detect click based on parent dropdown
- So, we can have multiple dropdown in one page and select will work based on its own parent
- Add (copy paste) dropdown html in storybook
- see selected …

AB#520 Fix dropdown behaviour

---

theme/core/grid/_grid.scss

- Spacing scss is included in the grid package
- Added CSS vars for spacing in the main grid.css to be able to be used through css as well
Fix: #27 [AB#519](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/519)
How to test:
Compile grid package
Use / import in a bare new app
See spacing CSS vars is added in the root html

AB#519 Add spacing vars into grid package

---

components/src/components/theme/grid.stories.js
theme/core/grid/_mixins.scss

- Added collapse option for push grid
- Added fix for push grid with non fluid container-putting the side-menu on the left of the entire window instead of next to the grid it self
Fixes: [AB#502](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/502)
- Run storybook
- Go to push grid
- Try and click collapse action and see it change the size of the side menu
- Zoom out
Compare with https://sdds-storybook.netlify.app/
- Zoom out and try non fluid and fluid

Push grid collapse and fix for non fluid push

---

demo/HTML/html.css
demo/HTML/package-lock.json
theme/core/typography/_selectors.scss
theme/core/typography/_typography.scss
theme/light/src/_variables.scss
theme/light/src/theme/sdds-theme.scss

- Restructure typography package
- Remove typography duplication in theme
Cause of bug:
- Error when importing theme light via script in the head
- relative path issues on duplicated font-face css
Fix #108 [AB#688](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/688)
- Run HTML demo, see error appears
- branch on PR
- Npm run build on theme-light & typography package
- Npm pack to create local package
- Install local package in HTML demo with "npm i file: ..\..\theme\core\typography\scania-typography-1.1.0.tgz"
- Install local package in HTML demo with "npm i file: ..\..\theme\scania-theme-light-2.2.0.tgz"
- See error is gone
- Try in angular demo as well
**Note: Somehow npm link doesn't work with angular 11, some …

AB#688 Remove font load duplication in scania theme light

---

components/src/helpers/core.js
components/src/helpers/index.js

- Use document.onreadystatechange which always fired instead of DOMContentLoaded event which sometimes fired in uncertain time.
- See docs: https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState
[AB#507](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/507) Fix #88
- Clone branch
- Build @scania/components
- Npm link to components from demo/angular or demo/react
- See styles being loaded after component loaded (no flash of unstyled content occured)
- Check in sdds-website, use npm link to check
_Add any other context about the …

AB#507 Fix#88 Use document readyState to fix FoUC

---

components/src/components/button/button.scss
components/src/components/button/button.stories.js
components/src/components/tooltips/tooltip.scss
components/src/components/tooltips/tooltip.stories.js
components/src/components/tooltips/tooltip.tsx

- Finished fixing the bug regarding the tooltip and <sdds-button>, with the tooltip not having the intended distance
Fixes: [AB#687](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/687) #106
- cd sdds
- npm start
- See in Storybook

AB#687 Fixed the bug regarding the distance with tooltip and <sdds-button>

---

components/src/components/textarea/readme.md
components/src/components/textarea/textarea.tsx
components/src/components/textfield/readme.md
components/src/components/textfield/textfield.stories.js
components/src/components/textfield/textfield.tsx
demo/HTML/package-lock.json
demo/angular/package-lock.json
demo/angular/src/app/app.module.ts
demo/angular/src/app/components/form/form.component.html
demo/angular/src/app/components/form/form.component.ts
demo/angular/src/app/components/form/input/input-component.html
demo/angular/src/app/components/form/input/input-component.ts
demo/angular/src/app/components/main/main.component.html

Created a Custom event that is composed=true to be able to use a change event in for example angular forms
There are multiple ways to add a web-component that contains an input in angular, but one thing that is a most is the attribute ngDefaultControl https://stackoverflow.com/questions/46465891/what-is-ngdefaultcontrol-in-angular
The custom event is called  customChange`(customChange)="logNgModel(usernameInput)"`
- Create template driven form in angular
- Created a reactive form in angular
- Added custom-input using Control Value Accessor
Additional fixes
Added autofocus on textfield and textarea
- Autofocus added on textfield and textarea
- Changed prop name for labelinside
_Add which issue this …

AB#252 - Added custom event to trigger change in a web component

---

theme/light/src/components/_link.scss

Fix [AB#801](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/801)
Link colour changed from blue-500 to blue-600
Fixes: #

AB#801 Change link colour

---

components/src/components/theme/theme.scss

Banner component doesn't work because import for it was removed.
Error can be found at digitaldesign.scania.com
added in alphabetical order
Fixes: #153 
2. Check banner

bug - Added back the banner import

---

components/src/components/dropdown/dropdown.tsx

- Added unique event listener
- Separate docs event listener and dropdown button event listener
Fix bug #141 [AB#818](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/818)
1. Checkout to the branch
2. Go to dropdown storybook (dropdown.stories.js) and add one more dropdown in Basic template (just copy paste, put it below the current dropdown)
3. Click the 2nd dropdown, while it's open, click the first one. The 2nd dropdown should close when clicking on the 1st one.

AB#818 Add unique id for each dropdown event listener

---

theme/core/grid/_mixins.scss

Fix for push grid non fluid having max-width
Fixing issue with push non fluid grid not having a max-width
1. Run storybook
2. Look at push grid with non-fluid
3. Container should have a max-width set now

Improvement - Fix for push grid non fluid having max-width

---

demo/angular/angular11/README.md
demo/angular/angular11/package.json
demo/angular/angular11/src/app/components/main/main.component.html
demo/angular/angular12/README.md
demo/angular/angular12/package.json
demo/angular/angular12/src/app/components/main/main.component.html
demo/angular/angular13/package.json
demo/angular/angular13/src/app/components/main/main.component.html

Adding difference in port number and main component file text to be able to easy spot which version of angular is running.
1. Run each version of angular
2. angular 11 on port 4211, angular 12 on port 4212, angular 13 on 4213

port and text change to differentiate angular version in browser

---

components/src/patterns/header/_navbar-collapsible.scss

Fix for issue in header mobile menu
Fixes: #
No official ticket, fixed on the fly.
1. Go to Storybook
2. Open Header component
3. Make sure to have TRUE next to show mobile menu in Storybook settings
4. Check if menu dropdown items look OK (position & padding)

mobile navigation menu in header fix

---

components/src/helpers/_utility-classes.scss

Scaling up the second level of utility classes for padding and margin
By mistake values for second-level remaind on value of 8px instead of 16px.

Scale up for second level values of utility classes

---

components/src/components/button/button.stories.js

In the button story in storybook, when enabling icons in the basic example, the icon won't show. I have added the import for web-font icons.
_Add description of how to test if possible_
1. Go to button story basic example
2. Try adding an icon with the control
3. Icon is now added
There are some improvement that needs to be done with the icon inside the button.

Improvement - Fix button story not showing icon in basic example

---

components/package-lock.json
components/package.json
components/src/components/accordion/accordion-item.tsx
components/src/components/accordion/accordion.scss
components/src/components/accordion/accordion.stories.js
components/src/components/accordion/readme.md

Fixing issue for right padding in accordion component
Fixes: [AB#1023](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1023)
1. Branch out branch OR open storybook from Netlify
2. Check Accordion component
3. There is a new Prop added called "paddingReset" 
4.  When "true" it resets right padding to 16px instead of 64px which is default

fix(accordion): reset prop for right-padding

---

components/src/components/card/card.stories.js
components/src/components/link/link.scss
components/src/components/link/link.stories.js

Introducing CSS class for controlling link underline appearance.
Fixes: [AB#982](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/982)  #187 
1. Go to Strotybook
2. Open Card component, select Link variation
3. Links in the Card component should not be underlined anymore
4. Now open Link component, select a Basic variation
5. In Storybook controls it should be "noUnderline" knob to test component with/without Underline

feat(link): add class for controling underline

---

package.json

Running sdds first time right after install won't work since the core packages hasn't been built,
this makes it run build right after install under prepare phase
If you clone a fresh sdds repo and run
- Npm i 
- npm start
It won't start, on master, because the theme will fail, reason for this is because the core packages hasn't been built yet. The core package don't have watchers, so every changes in those core packages needs to be built. Lerna start only starts the npm start command, which those packages doesn't have. Issue related with this #111 
This solves the issue so …

fix(starting-sdds): bug running sdds the first time

---

demo/react/src/App.js
demo/react/src/components/header/Header.js
demo/react/src/components/sideMenu/SideMenu.js

Expand or hide the side menu on mobile view in React demo
Fixes: [AB#1263](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1263)
1. Go to React Demo
2. Check in mobile view
3. Try to expand and hide side menu

Improvement - expand and hide side menu on mobile view in React

---

components/src/components/theme/utilites.stories.js
theme/light/src/_core.scss

Added import missing to be able to use sdds-text and background classes
Fixing issue with not being able to use for example `.sdds-text-blue-100`
- Added import missing from colour package
- Added new story to show off these options
_Add description of how to test if possible_
2. Go to story under utilities/colours
3. Check text example story, try and change colours
4. check background story, try and change colours
You can try and link these package on website repo 
Need to create a release for this fix

fix(sdds-theme): fixing but related with text and background classes

---

components/src/patterns/side-menu/side-menu.scss
components/src/patterns/side-menu/side-menu.stories.js
demo/react/package-lock.json
demo/react/package.json
demo/react/src/components/sideMenu/SideMenu.js
demo/react/src/index.css
demo/react/src/index.js
demo/react/src/index.scss

sticky collapse button on side menu in React demo 
Fixes: [AB#1372](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1372)
1. Go to React demo
2. Check in side menu collapse button
3. The button should be always shown on the bottom of screen and able to be focused when you tab around
I added few classes to our component package(components/src/patterns/side-menu/side-menu.scss)
and kept the same ones in React demo locally(demo/react/src/index.css) for now to see the result before we release the package. I'm planning to clean up the duplicate in React once we release it.
🤔  but please let me know if it's too much? perhaps it's better to make a PR for …

feat(side menu): sticky collapse button in react demo

---

components/src/components/dropdown/_dropdown-core.scss
components/src/components/dropdown/dropdown.scss
components/src/components/dropdown/dropdown.tsx
theme/light/src/components/_dropdowns.scss

Restyle dropdown to fit along with other inputs
- No border radius on bottom edges
- Border only on the bottom 
- Border color on different states
- default state: change to grey400
- hover state: change to grey600
- error state: change to semantic negative
- focus state: change to blue400 and width 2px
- active state: change to grey800
- disabled state: no border 
Figma: https://www.figma.com/file/jZONFYFlckRROjSVPPu2DD/Dropdown-exploration?node-id=2%3A163
Fixes: [AB#1114](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1114)
1. Go to storybook dropdown example
2. Check the look of dropdown in different state

style(dropdown): restyling dropdown to fit along with other inputs

---

components/src/components/dropdown/dropdown.scss
components/src/patterns/side-menu/side-menu.scss

1. Fixed the bug that opening the dropdown in side menu makes the option jump around. This is caused by border-left having 0.
2. Fixed Dropdown placeholder color on disabled state
Fixes: #258 
Fixes: [AB#1312](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1312)
1. Go to Storybook 
2. Check in side menu dropdown item alignment on opened state(you can compare it with current storybook example) 
3. Check in dropdown component placeholder color when it is disabled state it should be screenshot below

fix(side-menu): side menu dropdown item opened border fix

---

readme.md

Clarification that framework demos are run locally and how they're installed and run
Updated readme-file at root level. No longer a reference to repo directory, but a description on how to clone, install and run demos locally. 
N/A
1. Follow the steps on your local machine (clone, install and start) for each demo
2. Verify the described outcome, i.e. is able to open demos
N/A
No official issue, but I was personally confused and not helped by the guide when I tried to find the demos. Have tried myself for all framework demos.

docs(readme): readability update

---

components/.storybook/preview-body.html
components/.storybook/preview.js
components/src/components/theme/colour.stories.js
components/src/components/theme/fullpage.stories.js
components/src/components/theme/grid.stories.js
components/src/components/theme/spacing.stories.js
components/src/components/theme/typography.stories.js
components/src/components/theme/utilites.stories.js
components/src/patterns/footer/footer.stories.js
components/src/patterns/header/header.stories.js
components/src/patterns/side-menu/side-menu.stories.js

Solving issues with Storybook padding, margins, and centralizing content.
We used tricks to remove padding or margins set by stories.
There is a layout attribute that can be used instead, a very elegant solution for this issue.
More about it: https://storybook.js.org/docs/react/configure/story-layout
1. Open Storybook
2. All simple component stories need to be centralized
3. Other stories for full-screen components have set fullscreen layout property (header/footer/side menu/colors/....)

fix(storybook): using layout for arranging content in stories

---

components/.storybook/preview.js
components/package-lock.json
components/package.json
components/src/components/button/button.stories.js

> A retry on this PR since last PR https://github.com/scania-digital-design-system/sdds/pull/308 included edits of irrelevant files. 
- As a pilot project, only buttons are being snapshotted by chromatic. More stories can be added later by adding parameter to each story, read more here https://www.chromatic.com/docs/ignoring-elements
- Chromatic snapshot individual stories, so I've refactored button stories to represent all existing button variations (currently ~900).
Fixes: [AB#1335](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workit …

test(chromatic): visual testing for buttons

---

components/src/patterns/footer/footer.scss

This fixes the wordmark in the footer to always be right aligned.
Fixes: #1832

improvement/task-1832: Wordmark in footer is not right aligned

---

components/src/components/accordion/accordion-item.tsx
components/src/components/accordion/readme.md

Added an event named "accordionItemToggle" on the accordion item component which emits a boolean each time after that accordion item is opened/closed.

feat: accordion-item toggle event emitter

---

components/package-lock.json
components/package.json
components/src/components/dropdown/dropdown-filter.tsx
components/src/components/dropdown/dropdown.stories.js
components/src/components/dropdown/dropdown.tsx

Changing selected option dynamically
Fixes: [AB#1864](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1864)
1. Go to Storybook
2. Open the Dropdown component
3. Try to pass another option value in the selected option control
4. It should change the selected state in regular dropdown via: 
`document.getElementById('sdds-dropdown-reg').setAttribute('selected-option','option-3');`
5. It should change the selected state in filter dropdown via: 
`document.getElementById('sdds-dropdown-filter').setAttribute('selected-option','option-2');`

feat(dropdown): change selected option from outside

---

components/src/components/modal/modal.tsx

Opening the modal in a page with a height over the screen size makes for example the header height
smaller. What I have done is switch the overflow:hidden so it is on the html instead of body element.
This problem exist even without modal, if you set the body with overflow hidden
1. Open a page with a modal, the header component and a page that have the height bigger then screen (scrollbar)
2. Add the modal
3. Open them modal and see the header(video below)
Problem
https://user-images.githubusercontent.com/35451568/163327938-cbb26468-cb39-47b0-9ea8-c5b53d98a792.mov
Working example after …

fix(modal): there is a issue setting overflow:hidden on body 

---

components/src/components/tabs/inline-tabs/inline-tabs.scss
components/src/components/tabs/navigation-tabs/navigation-tabs.scss

fix: (tabs) fixed underline on hover state when showing tabs
Fixes: [AB#1957](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1957)
go to the storybook and see if the hover state on inline tabs and navigation tabs have "text-decoration: none;"

fix(tabs): remove underline on hover state when showing tabs

---

components/src/components/button/button.scss

Issue reported in our development channel with the button being display: flex
1. Go to Storybook example of button component
2. Inspect and see if display flex is gone
3. Compare the modal component between the link here and [prod Storybook](https://production.d1g8v8mrkx992n.amplifyapp.com/?path=/story/component-modal--modal)
4. In prod one, buttons are one below another, in fix one buttons are again next to each other with a gap between.
I introduced this issue with the last release

fix(button): remove display as flex

---

components/src/components/table/table.tsx

Table was not resetting search results after removing search criteria 
Fixes: #395 
1. Open Storybook on the link generated below
2. Go to the data table component and try to search
3. After you remove the search criteria, the table needs to show the original results 
4. Compare it with behavior on [prod Storybook ](https://production.d1g8v8mrkx992n.amplifyapp.com/?path=/story/foundation-colour--brand)where the bug still exists.

fix(table): reset search results if search query is empty

---

components/src/components/popover-menu/documentation.txt
components/src/components/popover-menu/popover-menu.scss
components/src/components/popover-menu/popover-menu.stories.js
components/src/components/popover-menu/popover-menu.tsx
components/src/components/popover-menu/readme.md
components/src/components/theme/theme.scss
sandbox/angular/src/app/components/home/home.component.html

A new component in the form of a Popover Menu, based on core-code from the popover canvas component.
Fixes: #2043
Go to the netlify link or checkout the branch, and browse to the PopoverMenu component. Click the kebab-dots to see it in action, both with and without icon.
Now with updated z-index to be correctly placed.

feat: popover-menu component 

---

components/src/components/breadcrumb/breadcrumb.scss
theme/light/src/components/_breadcrumb.scss
theme/light/src/theme/sdds-theme.scss

**Describe pull-request** 
Moving theming rules to component folder
Fixes: [AB#2214](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2214)
**How to test** 
1. Open breadcrums Storybook of this branch 
2. Open breadcrums Storybook of production 
3. Compare styling- there should not be any difference between those two

fix(breadcrums): moving theme rules to component folder

---

components/src/components/modal/_modal-core.scss
components/src/components/modal/modal-native.scss
components/src/components/modal/modal.scss
theme/light/src/components/_modal.scss
theme/light/src/theme/sdds-theme.scss

**Describe pull-request** 
Moving theming rules to component folder 
Fixes: [AB#2219](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2219) 
**How to test** 
1. Open modal in Storybook of this branch 
2. Open modal in Storybook of production 
3. Compare styling- there should not be any difference between those two

fix(modal): move theming rules to component folder

---

components/src/components/dropdown/_dropdown-core.scss
components/src/components/dropdown/dropdown.scss

The dropdown options were using a fixed background of white and hover of grey-50. This was only valid for the on-grey version.
The dropdown options were using a fixed background of white and hover of grey-50. This was only valid for the on-grey version. This PR makes the dropdown option use the variables "--sdds-dropdown-bg" and "--sdds-dropdown-bg-hover" which reflect the design. 
Fixes: [AB#1825](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1825)
1. In the storybook link below.
2. Check that the dropdown components in the on-white theme follows the design. 
3. Run -

fix(dropdown): changed the dropdown options to use the bg variables

---

components/src/components/header/header.scss

On the mobile menu, the active item indicator was displaying in the wrong position if the active item was a inline menu. This fixes that
Fixes: #362 [AB#1895](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1895)
1. Run SDDS
2. Edit Header story -> inline menu, so the item with the inline menu is the active one
3. Look at the story in Storybook
Before:
After:

fix(header): fix position of active item indicator when its on an inline menu

---

components/src/components/dropdown/dropdown-select.scss

Labels of native dropdowns were being placed with position absolute relative to the nearest positioned ancestor of the dropdown, instead of the dropdown itself, since the dropdown class had position set to static. 
This commit sets position relative on the dropdown, so the label is positioned relative to it.
Fixes: [AB#1826](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1826)
1. Check native dropdown in storybook
Before:
After:

fix(dropdown): fix misplaced native dropdown label

---

components/src/components/header/header.scss

Will hide the header menus with `opacity: 0` when they are not open, so they wont show briefly when the page loads. 
See: #347
This is a partial quick fix to a larger issue. 
The issue seems to happen on anything with a transition property defined on it. If i add a background color transition on sdds-btn, for example, it will fade in from the browser defaults on page load. 
I think its because the css is loaded in sdds-theme, so it might come in a bit late.
re #347, [AB#1931](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1931)
Go to this page, and refresh the page: https://production.d1g8v8mrkx992n.amplifyapp.com/iframe.html?args=&id=component-header--all-menus&viewMode=story

fix(header): stop dropdowns showing briefly on page load

---

components/src/components/dropdown/_dropdown-core.scss
components/src/components/dropdown/dropdown.scss

Places outside label variant of dropdown 8px above the dropdown, to align with appearance in figma, and also with appearance of text field. 
Also makes the label take up space on the page, which it did not previously do (it was placed with position absolute).
[AB#718](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/718)
Go here https://production.d1g8v8mrkx992n.amplifyapp.com/?path=/story/component-dropdown--label-outside,
or equivalent path on your localhost when running sdds.

fix(dropdown): place outside label 8px above dropdown like design spec

---

components/.storybook/preview.js

Not sure what was decided, but if we decided to change the default tab we can merge this PR.
Makes the docs tab the default tab in storybook, instead of canvas.

docs: make docs tab default in storybook

---

components/.storybook/preview.js

Shows code example by default in storybook.
Thought it felt better..
What do you think?

docs: show code example by default in storybook

---

components/package.json

Adds --quiet flag to `storybook-start` command to reduce the amount of unnecessary noise that appears in the console when running `npm start`
`npm start`
There was previously too much output in the console, to the point where it was a real chore to look through it.

chore: reduce noise when running npm start

---

tegel/.gitignore
tegel/src/global.d.ts

Add a type for .md files so it can be imported
Fixes: -
1. Run npm run tegel
2. Make sure it build properly and all readme files are imported correctly.
-
-

fix(global.d.ts): add a type for .md files so it can be imported

---

components/src/components/textfield/textfield.scss

Changed the sdds-textfield-helper to display flex and justify-content:between to allow for both the slot, error state and char counter to fit on the same row. 
Fixes: #524 [AB#2443](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2443)
2. Add a helper text on textfield, state to error and set a number on the char count. 
3. Check that all of these elements can be on the same row. 
Before:
After:
-

fix(textfield): display flex on sdds-helper to avoid clash between slot and char counter

---

components/src/components/textarea/readme.md
components/src/components/textarea/textarea.tsx
components/src/components/textfield/readme.md
components/src/components/textfield/textfield.tsx

A bug was found where to textarea/textfield components would not render in case they had null as their value. This is solved by instead adding a type to this value prop of string. This PR also updated the type-prop of the textfield component to expect 'text' or 'password'.
Fixes: #526
2. Check in componets -> textarea/textfield
3. Check that the component renders even though value is initially set to null. 
-
-

fix(textarea/textfield): handle-null-values-textfield/textarea

---

tegel/src/components/textarea/readme.md
tegel/src/components/textarea/textarea.tsx
tegel/src/components/textfield/readme.md
tegel/src/components/textfield/textfield.tsx

This PR updates tegel with updates Tegel to solve a bug that was found in 4_10.0.
PR that has been merged in 4_10.0: https://github.com/scania-digital-design-system/sdds/pull/557
Enables textarea/textfield to handle null as a value. This also updates the type for the type-prop for the textfield. 
Fixes: -
2. Check in components -> textfield/textarea
3. Check that the components renders with null as a value. 
-
-

fix(textarea/textfield):textarea/field to handle null values for tegel

---

components/src/components/tabs/inline-tabs/inline-tabs.stories.js
components/src/components/tabs/inline-tabs/inline-tabs.tsx

Made the component HTML compliant by making sure the inline tabs use data-name instead of name and aria-disabled="true" instead of disabled. Since the previous attributes isn't part of the global attributes we can't expects it's children to have those elements. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes
Fixes: [AB#2489](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2489)
1. Check the component in the sandbox and storybook
2. Make sure it's using data-* / aria-hidden attributes
3. Check that it renders and act in the expected way. 
-
-

fix(inline-tabs): make inline tabs html compliant

---

tegel/src/components/banner/banner.stories.ts

Add sdds-icon instead of hard-coded SVGs, default value fix
Fixes: Returning and fixing "TODO/FIXME comments after link and icon component are migrated"
1. Check if banner component looks the same as in [main branch](https://tegel-storybook.netlify.app/?path=/docs/components-banner--default).
2. Check if type and icon Control have "default" column filled with default value

fix(banner): add sdds-icon instead of hard-coded SVGs, default value fix

---

components/src/components/tabs/inline-tabs/inline-tabs.tsx

Corrrected the use of aria/data-disabled in getAttribute for the inline-tabs.
Fixes: corrects an error that was merged in: https://github.com/scania-digital-design-system/sdds/pull/561
2. Check in components -> inline-tabs
3. Check that the disabled state work as intended.
-
-

fix(inline-tabs): corrected the use of aria/data-disabled

---

theme/light/src/_core.scss

Removed import of color.vars since it's being imported in the color.sccs. 
Fixes: #370 [AB#1927](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1927)
1. Checkout branch and do npm linking to sdds-website
2. Run website
3. Check the css of the doc and check that the colours are only defined once.
-
-

fix(_core.scss): duplicate color variables generated

---

tegel/src/components/tabs/inline-tabs/inline-tabs.stories.ts
tegel/src/components/tabs/inline-tabs/inline-tabs.tsx

Makes inline-tabs html compliant, but keeps an option of using old way aswell.
Fixes: [AB#2493](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2493)
2. Check in Components -> inline-tabs
3. Check that the component uses valid HTML.
-
-

fix(inline-tabs): make inline-tabs valid html in tegel

---

tegel/package-lock.json
tegel/src/components/chips/chips.scss
tegel/src/components/chips/chips.stories.ts
tegel/src/components/stepper/stepper.scss
tegel/src/components/stepper/stepper.stories.js
tegel/src/stories/Migration/Migration.stories.mdx

👕 
Renames some classes to use two letter size keywords, like `sm` instead of `small`
Fixes: [AB#2303](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2303)
Checkout the Migration page is Storybook

feat: use two letter t-shirt sizes in class names

---

components/src/components/dropdown/dropdown.tsx
tegel/src/components/dropdown/dropdown.tsx
tegel/src/components/dropdown/readme.md

**Describe pull-request**
Dropdown with label inside is not rendering the label properly when no option is selected. Not changed for new Tegel components yet
Github issue https://github.com/scania-digital-design-system/sdds/issues/440 and Azure ticket [AB#2321](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2321)
**How to test**
- Go to storybook
- Check dropdown label inside and see if it looks correct

fix(dropdown): dropdown label inside full height

---

tegel/src/components/dropdown/dropdown.tsx

* Added a trim to the optionLabels to remove linebreaks.
* Fixed placeholder to support inside labels on multiselect.
Fixes: [AB#2495](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2495)
2. Check in Components -> Dropdown Webcomponent Multiselect
3. Check that the labels show the selected options and if nothing is selected it shows placeholder.
-
-

fix(dropdown): multiselect dropdown doesnt show option labels

---

tegel/package-lock.json
tegel/package.json

I had removed prettier in the tegel package, thinking that we only used that for linting while developing, when we're in-fact using it to format code examples in storybook as well.
This PR re-adds prettier to the tegel packages dependencies.

build: fix build failing on netlify

---

tegel/src/components/textarea/textarea.tsx
tegel/src/components/textfield/textfield.scss
tegel/src/components/textfield/textfield.tsx

Added check for null values for char count correct css for textfield count.
Fixes: [AB#2574](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2574)
2. Check in Components -> Textfield/Textarea
3. Add a char counter with and without a state and see that it renders correctly.
-
-

fix/textfield state count issues - tegel

---

tegel/src/components/popover-canvas/popover-canvas.stories.ts
tegel/src/components/popover-menu/popover-menu-icons.stories.ts
tegel/src/components/popover-menu/popover-menu.stories.ts

Removed the hard-coded svg and replaced it with our own webcomponent. 
Fixes: [AB#2579](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2579)
2. Check in Components -> Popover Cavas/Menu
3. Check that all the icons are rendered correctly.
-
-

fix(popovercanvas/menu): added sdds-icon instead of SVG

---

tegel/.storybook/main.js
tegel/.storybook/manager-head.html
tegel/.storybook/manager.js

Google Analytics without Storybook addon
Using code from the "Install manually" option of Google Analytics

feat(storybook): adding Google Analytics without addon

---

tegel/.storybook/manager-head.html

Reverting hard coded values as Netlify is failing to build.
Let's test if leaving code as is will work.
We need to merge this one as only when it is merged and built, we can check if we get any data in the google analytics board.

fix(storybook): reverting hard coded values for GA due to Netlify error

---

tegel/src/components/toast/toast.scss
tegel/src/components/toast/toast.stories.ts

Added color to the wrapper class of the icon and added the possibility to pick icons from toast
Fixes: [AB#2583](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2583) [AB#2595](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2595)
2. Check in Components -> Toast
3. Check that the controls for the icons work as intended.
-
-

fix(toast): added color to the wrapper class of the icon

---

tegel/package-lock.json
tegel/package.json
tegel/src/components/link/link.stories.ts

Removed clsx package from link story.
Fixes: [AB#2578](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2578)
2. Check in Components -> Link
3. Check that the controls and template are still correct.
-
-

docs(link): remove clsx package

---

components/src/components/icon/icon.tsx

Reverted the dynamic import of icon package to @scania/icons instead of local folder
Fixes: -
1. Check out the branch
2. Run npm start in components folder
3. Check in storybook that the icons component still works as intended.
-
-

fix(icon): dynamic import of scania/icons for icon-component

---

tegel/src/components/checkbox/checkbox.stories.ts

Added conditional logic to render empty string if not disabled.
Fixes: [AB#2683](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2683)
2. Check in Components -> Checkbox
3. Check that the template and preview are both correct.
-
-

fix(checkbox): removed unused false prop on checkbox.

---

tegel/src/components/checkbox/checkbox.scss
tegel/src/components/datetime/datetime.scss
tegel/src/components/dropdown/dropdown-select.scss
tegel/src/components/radio-button/radio-button.scss
tegel/src/components/textarea/textarea.scss
tegel/src/components/textfield/textfield.scss

Adding not-allowed cursor to component that missed it
Fixes: [AB#2476](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2476)
1. Open Netlify build link
2. Check the disabled state of "affected" components
3. Make sure they have not-allowed cursor once in a disabled state
**Components affected**  
1. Checkbox
2. Datetime
3. Dropdown (native)
4. Radio button
5. Textarea
6. Textfield
Link and Inline Tabs have `pointer-events: none` which blocks not-allowed cursor. They would need to be changed to do this change so I am leaving them as is. It seems better that they remain with that rule as it prevents clicking better then disabled state.

fix: adding not-allowed cursor to disabled state

---

tegel/src/components/badges/badges-component.tsx
tegel/src/components/badges/readme.md
tegel/src/components/button/button-component.tsx
tegel/src/components/spinner/spinner.tsx
tegel/src/components/textarea/readme.md
tegel/src/components/textarea/textarea.stories.ts
tegel/src/components/textarea/textarea.tsx
tegel/src/components/textfield/readme.md
tegel/src/components/textfield/textfield.stories.ts
tegel/src/components/textfield/textfield.tsx
tegel/src/stories/Migration/Migration.stories.mdx

Altered some props to be camelCased to conform with naming convention.
Fixes: [AB#2487](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2487)
2. Check in Components -> Textfield/Textarea
3. Check that the stories and components are still working.
4. Check the migration doc and see if the purposed solution makes sense. 
-
-

fix/make all props camelCase

---

tegel/src/components/chips/chips.stories.ts

The deprecated class name `sdds-chip__small` was showing ing docs.
This restores `sdds-chip-sm`

docs(chips): fix docs showing deprecated class name

---

tegel/src/components/data-table/table-body-cell/table-body-cell.tsx
tegel/src/components/data-table/table-body-row-expandable/table-body-row-expandable.tsx
tegel/src/components/data-table/table-body-row/table-body-row.tsx
tegel/src/components/data-table/table-body/table-body.tsx
tegel/src/components/data-table/table-component-basic.stories.ts
tegel/src/components/data-table/table-component-batch-actions.stories.ts
tegel/src/components/data-table/table-component-custom-width.stories.ts
tegel/src/components/data-table/table-component-event-listeners.stories.ts
tegel/src/components/data-table/table-component-expandable-rows.stories.ts
tegel/src/components/data-table/table-component-filtering.stories.ts
tegel/src/components/data-table/table-component-pagination.stories.ts
tegel/src/components/data-table/table-component-sorting.stories.ts
tegel/src/components/data-table/table-footer/table-footer.tsx
tegel/src/components/data-table/table-header-cell/table-header-cell.tsx
tegel/src/components/data-table/table-header/table-header.tsx
tegel/src/components/data-table/table-toolbar/table-toolbar.tsx
tegel/src/components/data-table/table/readme.md
tegel/src/components/data-table/table/table.tsx

Since the id attribute was required for datatable to work, this PR replaces it with a tableId property in the web-component. The property is automatically initialised to a random string so the user doesn't have to set it themselves.

feat(datatable): use required prop for id instead of id attribute

---

tegel/src/components/button/button-native.stories.ts
tegel/src/components/button/button-webcomponent.stories.ts

Added readme to notes for webcomponent button
Fixes: [AB#2678](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2678)
2. Check in Components -> Button -> Webcomponent
3. Check that the notes tab contains the correct readme.md
-
-

docs(button): added readme to notes for webcomponent button

---

tegel/src/components/tooltip/tooltip.stories.ts
tegel/src/components/tooltip/tooltip.tsx

Added show on focus and removed bad lint naming, changed '_this' to 'thisValue'. Exposed the slot as a control in storybook. Wrapped template in formatHtmlPreview.
Fixes: [AB#2641](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2641) [AB#2646](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2646)
2. Check in Components -> Tooltip
3. Try tabbing through the page and test if the tooltip shows
-
-

fix(tooltip): added show on focus and removed bad lint naming

---

tegel/.storybook/preview.js

Removed the parameter setting docs as the default tab.
Fixes: [AB#2729](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2729)
2. Check in a couple of random stories.
3. Make sure canvas is the default tab.
-
-

docs(canvas): made canvas the default tab

---

tegel/src/components/side-menu/side-menu.scss
tegel/src/components/side-menu/side-menu.stories.ts
tegel/src/stories/Migration/Migration.stories.mdx

BREAKING CHANGE: Changed all invalid anchors to buttons for the side-menu, also updated in migration docs
Changed all <a> being used as buttons to simple buttons instead. Also updated the migration docs.
Fixes: [AB#2706](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2706)
2. Check in Components -> Side-menu
3. Check that the close/expand buttons still works as intended.
-
-

fix(side-menu): changed anchors to buttons for side-menu

---

tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.ts
tegel/src/components/dropdown/dropdown-wc-default.stories.ts
tegel/src/components/dropdown/dropdown-wc-multiselect.stories.ts

Adding missing controls to Dropdown filter component (label position, state, label text)
Fixes: [AB#2577](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2577)
1. Open Netlify PR link
2. Go to the Dropdown-filter component
3. Check if controls there are as in regular Dropdown WebComponent variation
Dropdown-filter seems not to accept label-inside as an option so one is removed from Storybook controls. I am adding a ticket for it for further investigation.

docs(dropdown-filter): adding missing controls

---

tegel/src/components/accordion/accordion-item/accordion-item.tsx
tegel/src/components/accordion/accordion-item/readme.md
tegel/src/components/accordion/accordion.scss
tegel/src/components/accordion/accordion.stories.ts
tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.ts
tegel/src/components/dropdown/dropdown-wc-default.stories.ts
tegel/src/components/dropdown/dropdown-wc-multiselect.stories.ts
tegel/src/stories/Migration/Migration.stories.mdx

- Renames accordion item affix attribute to expand-icon-position.
- Slims down accordion story.
Fixes: [AB#2642](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2642)

feat(accordion): rename affix

---

tegel/.storybook/main.js

Removes a rouge comma to bring back the docs tab in storybook as well as the controls.

docs: fix docs and controls gone in storybook

---

tegel/src/components/badge/badges.scss

Changed bg-color of the badge to use correct (--sdds-negative) color.
Fixes: [AB#2677](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2677)
2. Check in Components -> Badge
3. Check that the bg of the badge is the correct --sdds-negative.
-
-

fix(badge): used correct color

---

tegel/src/components/textarea/textarea.scss

The textarea width did was not used on disabled state due to it being part of the focus state css (which was removed from disabled). This PR refactors the css to include the width, min-width and positioning for all states.
Fixes: [AB#2709](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2709)
2. Check in Components -> Textarea
3. Check that the component behaves as expected for all states. 
-
-

fix(textarea): refactored css so width styles is used for all states

---

tegel/src/components/textarea/readme.md
tegel/src/components/textarea/textarea.tsx
tegel/src/stories/Migration/Migration.stories.mdx

Changed readonly and autofocus props to camelCase to conform with other propnames
BREAKING CHANGE: Changed readonly to read-only and autofocus to auto-focus
Fixes: [AB#2744](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2744)
2. Check in Components -> Textarea
3. Check the props in the story and the migration.mdx
-
-

fix(textarea): changed readonly and autofocus props to camelCase

---

tegel/src/components/toggle/toggle.stories.ts

Added `disabled` prop to native input element. 
Fixes: [AB#2652](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2652)
2. Check in Components -> Toggle
3. Set the component in disabled state
4. Set focus on the element and try to toggle it using space/enter.
-
-

fix(toggle): added disable prop to native input element

---

tegel/src/components/block/block.scss
tegel/src/components/block/block.stories.ts
tegel/src/components/textfield/textfield.stories.ts
tegel/src/stories/Migration/Migration.stories.mdx

BREAKING CHANGE: Changed the class names sdds-block__default and sdds-block__variant to single dash, sdds-block-default and sdds-block-variant
Changed sdds-block__default/variant to single dash names. 
Fixes: [AB#2700](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2700)
2. Check in Components -> Block
3. Check that the style of the component is correct.
4. Check the migration.mdx. 
-
-

fix(block): changed the class names for block to conform with convention

---

tegel/src/components/tabs/navigation-tabs/navigation-tabs.scss
tegel/src/components/tabs/navigation-tabs/navigation-tabs.stories.ts
tegel/src/components/tabs/navigation-tabs/navigation-tabs.tsx
tegel/src/stories/Migration/Migration.stories.mdx

Refactored both the external and the components internal class names to conform with convention (single dash). Also updated the migration.mdx
BREAKING CHANGE: Classes the previously had -- or __ was changed to single dash.
Fixes: [AB#2702](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2702)
2. Check in Components -> Tabs -> Navigation tabs
3. Check that the component has the correct styling and that the migration.mdx updates makes sence.
-
-

fix(navigation-tabs): changed the class names for navigation-tabs to conform with convention

---

tegel/src/components/accordion/accordion-item/accordion-item.tsx
tegel/src/components/accordion/accordion-item/readme.md
tegel/src/components/accordion/accordion.scss
tegel/src/components/icon/readme.md

Corrected panel expanded padding and used sdds-icon instead of svg for the chevron.
Fixes: [AB#2656](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2656)
2. Check in Components -> Accordion
3. Check the padding on the expanded panel.
4. Check the chevron icon.
-
-

fix(accordion): padding and chevron fixes

---

tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.ts
tegel/src/components/side-menu/side-menu.stories.ts

Capital letters to story names
Fixes: [AB#2648](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2648)
1. Go to the Netlify preview link
2. Check that the Side menu and Dropdown filter have capital letters for all words in the story name
Introduction stories I have left as they are.

fix: capital letters to story names

---

tegel/src/components/textfield/textfield.scss
tegel/src/components/textfield/textfield.tsx

Added a class to get the state of the textfield in the icon and added the correct color to this icon if state === 'error'.
Fixes: [AB#2741](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2741)
2. Check in Components -> Textfield
3. Add a suffix and/or prefix icon and set the component to error state.
-
-

feat(textfield): added color to suffix/prefix icons

---

tegel/src/components/modal/modal.scss

Added a 16px gap between buttons on modal.
Fixes: [AB#2671](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2671)
2. Check in Components -> Modal -> Web component
3. Check that there is a 16px gap between the buttons on the modal.
-
-

feat(modal): added 16px gap between buttons on modal

---

tegel/src/components/textarea/readme.md
tegel/src/components/textarea/textarea.stories.ts
tegel/src/components/textarea/textarea.tsx
tegel/src/components/textfield/readme.md
tegel/src/components/textfield/textfield.scss
tegel/src/components/textfield/textfield.stories.ts
tegel/src/components/textfield/textfield.tsx
tegel/src/stories/Migration/Migration.stories.mdx

Changed the label/labelPosition props to align the component with each other. After this change both components have label="Label text" and label-position="inside | outside | no-label". 
Fixes: [AB#2742](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2742)
2. Check in Components -> Textarea/Textfield
3. Check that the controls and the example code works as they should.
-
-

fix(textarea/textfield): label position label props

---

tegel/src/components/textfield/readme.md
tegel/src/components/textfield/textfield.stories.ts
tegel/src/components/textfield/textfield.tsx
tegel/src/stories/Migration/Migration.stories.mdx

Changed the prop name to conform with convention and refactored story to include a demo-wrapper.
BREAKING CHANGE: Changed the prop name from nominwidth to no-min-width
Fixes: [AB#2743](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2743)
2. Check in Components -> Textfield
3. Check that the no-min-width prop works as intended. Also check the migration.mdx.
-
-

fix(textfield): changed the nominwidth prop to noMinWidth

---

tegel/.storybook/main.js
tegel/package-lock.json
tegel/package.json

Need to add an .env file in tegel dir with the line "STORYBOOK_ENV=development" locally

chore: make sb addons work in dev mode

---

tegel/readme.md

Adds a readme for the tegel package.
Fixes: [AB#2485](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2485)
**How to test**
Go to branch and look at readme
Link: https://github.com/scania-digital-design-system/sdds/tree/docs/add-tegel-readme/tegel#readme

docs: add a readme for the tegel package

---

components/src/components/accordion/accordion.scss

Since this css cover both accordion and accordion-item the css rules can't specifiy a host within a host so this is why I changed it to sdds-accordion.
Fixes: [AB#2747](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2747)
1. Check out branch and run components.
2. Add a sdds-on-white-bg class to the accordion in its story.
3. Check that the hover state is correct.
-
-

fix(accordion): css rules for accordion

---

components/src/components.d.ts
components/src/components/dropdown/dropdown-option.tsx
components/src/components/dropdown/dropdown.scss
components/src/components/dropdown/dropdown.stories.js
components/src/components/dropdown/readme.md
tegel/src/components/badge/badge.stories.ts
tegel/src/components/dropdown/dropdown-option/dropdown-option.tsx
tegel/src/components/dropdown/dropdown-option/readme.md
tegel/src/components/dropdown/dropdown-wc-default.stories.ts
tegel/src/components/dropdown/dropdown-wc-multiselect.stories.ts
tegel/src/components/dropdown/dropdown.scss

Adding disabled state to dropdown option
Fixes: [AB#2549](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2549) #589 
1. Go to the dropdown component
2. In both the default web component and multi-select one, there is one item that is disabled
3. Try to select it, it should not be possible
Currently, this fix is not involving filtering type of dropdown. 
The feature is done for both the component and Tegel package
The design of a disabled state has to be verified by one of our designers.

feat(dropdown-option): adding disabled state

---

components/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
components/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.stories.js
components/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.tsx
components/src/components/tabs/inline-tabs-fullbleed/readme.md
components/src/components/tabs/inline-tabs/inline-tabs.scss
components/src/components/tabs/inline-tabs/inline-tabs.stories.js
components/src/components/tabs/inline-tabs/inline-tabs.tsx
components/src/components/tabs/inline-tabs/readme.md
tegel/src/components/tabs/inline-tabs-default/inline-tabs.scss
tegel/src/components/tabs/inline-tabs-default/inline-tabs.stories.ts
tegel/src/components/tabs/inline-tabs-default/inline-tabs.tsx
tegel/src/components/tabs/inline-tabs-default/readme.md
tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.stories.ts
tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.tsx
tegel/src/components/tabs/inline-tabs-fullbleed/readme.md

Added a variant prop to allow user to use the on white/on grey options. 
Fixes: [AB#2751](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2751)
1. Check out the branch and run start for components.
2. Check in that the variant controls works as intended. 
3. Check the storybook link below.
4. Check in that the variant controls works as intended for tegel. 
-
-

feat(inline-tabs/inline-tabs-fullbleed): added variant prop

---

tegel/src/components/chips/chips.scss
tegel/src/components/chips/chips.stories.ts

Added the for the web font icon to the component styling. Removed unused styles from story.
Fixes: [AB#2819](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2819)
2. Check in Components -> Chip
3. Add a native icon and make sure it's 16px in font-size.
-
-

fix(chips): added font-size for icon in component css

---

tegel/src/components/header/header-all.stories.ts
tegel/src/components/header/header-default.stories.ts
tegel/src/components/header/header-inline.stories.ts
tegel/src/components/header/header-search.stories.ts
tegel/src/components/header/header-toolbar.stories.ts

Removed controls since js make demo interactive.
Fixes: [AB#2828](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2828)
2. Check in Components -> Header
3. Check that the only control is for the application name.
-
-

docs(header): removed controls since js make demo interactive

---

tegel/src/components/data-table/native-table.scss

Corrected the height of the caption for native component.
Fixes: [AB#2825](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2825)
2. Check in Components -> Data-table -> Native
3. Check that the caption is 64px by default and 56px in compact design
-
-

fix(data-table): native component caption fixes

---

tegel/src/components/data-table/table-component-multiselect.stories.ts

Added a default value for the multiselect story.
Fixes: [AB#2824](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2824)
2. Check in Components -> Data-table -> Multiselect
3. Check that multiselect is enabled by default.
-
-

docs(data-table): added default value for multiselect

---

tegel/src/global/global.scss
tegel/src/global/scania-fonts-selectors.scss

Removed tegel dependancy on scania/typography package.
This is an alternative to https://github.com/scania-digital-design-system/sdds/pull/710
Fixes: [AB#2830](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2830)
2. Check in typography
3. Check that the font are correct and that they are using rem for font-size and no unit for line-height.
-
-

feat(typography): removed dep on scania/typography

---

tegel/src/components/modal/modal-webcomponent.stories.ts
tegel/src/components/modal/modal.tsx
tegel/src/components/modal/readme.md
tegel/src/stories/Migration/Migration.stories.mdx

Refactored how we open the modal and removed prop selector, updated the story and added to migration docs
BREAKING CHANGE: Removed the selector prop and added prop for open.
Fixes: [AB#2739](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2739)
2. Check in Components -> Modal -> Web component
3. Check that the modal works as expected.
4. Check the added chapter in migration docs.
**Screenshots** 
-
**Additional context** 
-

feat(modal): refactored how we open the modal and removed prop selector

---

tegel/src/components/accordion/accordion.scss

In a former PR this seems to have been lost. Adding a bottom border to the last child of the accordion.
Fixes: -
2. Check in Components -> Accordion
3. Check that the accordion has a bottom border of 1px.
-
-

fix(accordion): added bottom border to last child

---

tegel/src/components/banner/banner.stories.ts
tegel/src/components/data-table/table-body/table-body.tsx
tegel/src/components/data-table/table-component-batch-actions.stories.ts
tegel/src/components/footer/footer.stories.ts
tegel/src/components/header/header-all.stories.ts
tegel/src/components/header/header-inline.stories.ts
tegel/src/components/header/header-search.stories.ts
tegel/src/components/header/header-toolbar.stories.ts
tegel/src/components/icon/icon-web-component.stories.ts
tegel/src/components/message/message.stories.ts
tegel/src/components/popover-canvas/popover-canvas.stories.ts
tegel/src/components/popover-menu/popover-menu-icons.stories.ts
tegel/src/components/popover-menu/popover-menu.stories.ts
tegel/src/components/side-menu/side-menu.stories.ts
tegel/src/components/stepper/stepper.stories.ts
tegel/src/components/textfield/textfield.stories.ts

Removed all instances of solfclosures on our custom elements. See: https://stackoverflow.com/questions/23961178/do-custom-elements-require-a-close-tag
Fixes: [AB#2750](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2750)
2. Check in Foundations -> Icon
3. Check that the component still renders as intended
-
-

fix(sdds-icon): removed all selfclosures

---

tegel/src/components/button/button.scss

Corrected the margin left for button icon.
Fixes: [AB#2838](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2838)
1. Go to Components -> Button -> Native With Icon
2. Check the margin of the icon and make sure its 28px for lg. 
-
-

fix(button): corrected the margin left for button icon

---

tegel/src/components/modal/modal-native.stories.ts
tegel/src/components/modal/modal.scss
tegel/src/components/modal/modal.tsx
tegel/src/components/toast/toast.scss
tegel/src/components/toast/toast.stories.ts
tegel/src/stories/Migration/Migration.stories.mdx

Unifies close button class naming.
Fixes: [AB#2748](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2748)
Look at the affected components in the deploy preview.

feat: rename close btn classes

---

components/src/components/modal/modal.tsx

Removed stopPropogation on modal to allow clicks within the modal.
Fixes: -
1. Check out branch and run npm start in components
2. Check in Components -> Modal -> Webcomponent
3. Check that the buttons work as intended within the modal.
-
-

fix(modal): removed stopPropogation on modal click

---

tegel/src/components/data-table/native-table.scss
tegel/src/components/data-table/native-table.stories.ts

- Rewrites native table css to classes are not needed
- Removes classes from story
- Removes undocumented left over classes from web component transition
- Makes table a little smaller to minimise the code example
Note: This should not be a breaking change, as it still works with the classes (they just don't do anything), and the other removed classes were undocumented.
Fixes: [AB#2852](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2852)
Check native table in storybook in the link below.

feat: rewrite native table css to classes are not needed

---

tegel/src/components/datetime/datetime.scss
tegel/src/components/datetime/datetime.stories.ts
tegel/src/components/datetime/datetime.tsx
tegel/src/components/datetime/readme.md
tegel/src/components/icon/readme.md
tegel/src/stories/Migration/Migration.stories.mdx

Removed the slots for label/helper and created props for them instead, also introduces the prop
default-value to allow the user to select a default time to be displayed.
Fixes: [AB#2837](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2837)
2. Check in Components -> Date-time
3. Check that the controls regarding label/helper works as inteded.
4. Try out the new custom/now value for default-value.
-
-

fix(date-time): align props date time and introduce default-value

---

components/src/components/modal/_modal-core.scss
components/src/components/modal/modal.tsx

Removes the "after" on the modal toolbar and added padding-bottom to prevent constant overflow.
Fixes: -
1. Checkout and run start for components package.
2. Check in Components -> Modal
3. Check that modal that should not have overflow (little body text) does not have a scrollbar.
-
-

fix(modal): fix the constant overflow on modal

---

tegel/src/components/radio-button/radio-button.stories.tsx

Fixes some things in the radio buttons storybook example. See the code changes!
Thought: we might want to include a css reset for the `fieldset` element
Fixes: [AB#3010](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3010)

docs: fix radio storybook example

---

tegel/src/components/button/button-native.stories.tsx
tegel/src/components/button/button-webcomponent.stories.tsx

Removing control for text in "only icon" button stories
Fixes: [AB#2956](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2956)
1. Go to PR preview link
2. Check Button stories with "Only Icon"
3. Text control should be hidden for these two

docs(button): hide text control in "only icon" stories

---

tegel/src/components/popover-canvas/popover-canvas-theme-vars.scss

Fixes bug introduced in #748
(Text in popover canvas was white even outside of darkmode)

fix: popover canvas color

---

tegel/src/components/modal/modal-native.stories.tsx
tegel/src/components/modal/modal-webcomponent.stories.tsx
tegel/src/components/modal/modal.scss

Fixes for modal:
- body text cut when sticky position of the action bar is set
- padding on right missing on smaller width screen sizes
- enabling control for body text for easier testing
- dropping extra class from story example
Fixes: [AB#2849](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2849)
1. Go to the Netlify PR link
2. Add a lot of text to the body and see if text display correctly, no matter sticky/static action bar position
3. Check if padding-right on body-text area looks good on all screens
In case you are curios to understand the problem better, try running the current master branch and modal, you will see there is an issue with …

fix(modal): fix body text spacing

---

components/src/components/dropdown/dropdown-select.scss
components/src/components/dropdown/dropdown.stories.js
tegel/src/components/dropdown/dropdown-select.scss

Aligned the styling of the disabled state for native and wc version of dropdown.
Fixes: [AB#3022](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3022)
**How to test - Tegel**  
2. Check in Components -> Dropdown -> Native
3. Toggle the disabled state and check that the styling is correct.
**How to test - scania/components**  
1. Checkout branch and run storybook
2. Check in Components -> Dropdown -> Native Select
3. Toggle the disabled state and check that the styling is correct.

feat(dropdown-native): correct styling for disabled dropdown

---

tegel/src/components/tooltip/tooltip.stories.tsx

The tooltip-story was broken due to a comment in the html-element. Moved it above it.
Fixes: -
2. Check in Components -> Tooltip
3. Check that the story works.
-
-

fix(tooltip): moved comment out of element to not break story

---

tegel/src/components/toggle/readme.md
tegel/src/components/toggle/sdds-toggle.scss
tegel/src/components/toggle/sdds-toggle.stories.tsx
tegel/src/components/toggle/sdds-toggle.tsx
tegel/src/components/toggle/toggle.stories.tsx

Web component version of the toggle. Also renamed toggle native story to "Native".
ShadowDOM is removed in order for the component to work within a form.
Fixes: [AB#3144](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3144)
1. Go to story book link below
2. Check in Component -> Toggle -> Web Component
3. Check that styling and functionality is correct

feat(toggle): webcomponent

---

tegel/src/components/button/button-component.tsx
tegel/src/components/button/button-native.stories.tsx
tegel/src/components/button/button-webcomponent.stories.tsx
tegel/src/components/button/button.scss

Corrected the css selector for the only-icon button. Also removed the prop onlyIcon being set in the story, this prop doesn't exist. It is an internal state that is set based on the text value. The old way would lead to the component not being rendered properly.
Fixes: - Found this issue when I was implementing the button in the banner component.
2. Check in Components -> Button -> Web Component Only Icon
3. Check that no prop is being set if only icon is true and that the component renders as i it should-
-
-

fix(button): only icon button

---

tegel/src/components/icon/readme.md
tegel/src/components/textarea/readme.md
tegel/src/components/textarea/textarea.scss
tegel/src/components/textarea/textarea.tsx
tegel/src/components/textfield/readme.md
tegel/src/components/textfield/textfield-theme-vars.scss
tegel/src/components/textfield/textfield.scss
tegel/src/components/textfield/textfield.stories.tsx
tegel/src/components/textfield/textfield.tsx
tegel/src/stories/Migration/Migration.stories.mdx

This PR adds a error icon to the textarea when it is set to the error state. This PR also removes the slot `sdds-helper` and instead introduces the value as a prop for the **textfield**, like it is in other components. Also changed the error state colors on the textfield-
Fixes: [AB#3169](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3169)
**How to test - 1**  
2. Check in Components -> Textarea
3. Set the component to error state and check that the design is correct.
**How to test - 2**  
2. Check in Components -> Textfield
3. Add an helper text to the component and check that it is rendered correctly.
4. Check out the …

fix(textarea & textfield) error state and aligned props

---

tegel/src/components/chips/chips.scss
tegel/src/components/chips/chips.stories.tsx
tegel/src/stories/Migration/Migration.stories.mdx

BREAKING CHANGE: The classes __small, __active and __icon-right/left was renamed to conform with our convention of classnames
The classes __small, __active and __icon-right/left was renamed to conform with our convention of classnames
Fixes: -
2. Check in Components -> Chips -> Native
3. Check that the styling is correct and that the controls function as before.
4. Have a look at the Chip section in the migration docs.
-
-

feat(chip): renamed classes to align with convention

---

tegel/src/components/dropdown/dropdown-theme-vars.scss
tegel/src/components/link/link-theme-vars.scss
tegel/src/components/link/link.stories.tsx
tegel/src/components/link/readme.md
tegel/src/components/link/sdds-link.scss
tegel/src/components/link/sdds-link.stories.tsx
tegel/src/components/link/sdds-link.tsx

Webcomponent version of link. Also renamed native story.
Removed shadowDOM in order to handle visited state.
Fixes: [AB#3163](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3163)
2. Check in Components -> Link -> Webcomponents
3. Check that the style is correct.

feat(link): webcomponent

---

components/src/components/tabs/inline-tabs/inline-tabs.stories.js
components/src/components/tabs/inline-tabs/inline-tabs.tsx

Fixed bug with buttons not being based on the widest one.
Fixes: [AB#3291](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3291)
1. Checkout branch
2. Run storybook for component package
3. Check that the button width for the inline tabs are based on the widest one.

fix(inline-tabs): width of buttons

---

tegel/src/components/checkbox/checkbox.scss
tegel/src/components/checkbox/checkbox.stories.tsx
tegel/src/components/checkbox/readme.md
tegel/src/components/checkbox/sdds-checkbox.scss
tegel/src/components/checkbox/sdds-checkbox.stories.tsx
tegel/src/components/checkbox/sdds-checkbox.tsx

Web component version of the checkbox. Also renamed checkbox native story to "Native".
ShadowDOM is removed in order for the component to work within a form.
Fixes: [AB#3158](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3158)
1. Go to story book link below
2. Check in Component -> Checkbox -> Web Component
3. Check that styling and functionality is correct

feat(checkbox): webcomponent

---

tegel/src/components/data-table/table-body-row-expandable/table-body-row-expandable.scss

Switched visibility collapse to display:none. Collapse has bad browser support.
Fixes: [AB#3025](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3025)
2. Check in Components -> Data table -> Expandable rows
3. Check that the row can hide/expand correctly.
4. Make sure to test in safari/firefox.

fix(expandable table): safari bug

---

tegel/readme.md
tegel/src/stories/Events/Events.stories.mdx

Documentation on event naming convention - both internal and external.
Fixes: [AB#3299](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3299)
2. Check in Tegel - events
3. Check the readme of this PR: https://github.com/scania-digital-design-system/sdds/tree/docs/event-documentation/tegel

docs(event): documentation of event naming convention

---

tegel/src/components/checkbox/readme.md
tegel/src/components/checkbox/sdds-checkbox.tsx

Removed a unsused prop - label. The label is populated via the slot.
Fixes: -
2. Check in Components -> Checkbox -> Web Component
3. Check the readme and that all the props are usable.

fix(checkbox): remove usused prop - label

---

tegel/src/components/accordion/accordion.tsx
tegel/src/components/button/button-component.tsx
tegel/src/components/card/card.stories.tsx
tegel/src/components/message/message-theme-vars.scss
tegel/src/components/message/message.stories.tsx
tegel/src/components/message/readme.md
tegel/src/components/message/sdds-message.stories.tsx
tegel/src/components/message/sdds-message.tsx
tegel/src/components/tabs/inline-tabs-default/inline-tabs.tsx
tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.tsx
tegel/src/components/tabs/navigation-tabs/navigation-tabs.tsx
tegel/src/components/textarea/readme.md
tegel/src/components/textarea/textarea.stories.tsx
tegel/src/components/textarea/textarea.tsx
tegel/src/components/textfield/readme.md
tegel/src/components/textfield/textfield.tsx

Card, message, textfield and textarea was missing null option to mode variant and/or Inherit from parent as option in storybook
Check the components and that mode variants working in storybook and looks ok in code

fix: mode variant add null and inherit from parent to components

---

tegel/src/components/toggle/sdds-toggle.scss
tegel/src/components/toggle/sdds-toggle.tsx
tegel/src/components/toggle/toggle-theme-vars.scss
tegel/src/components/toggle/toggle.scss
tegel/src/components/toggle/toggle.stories.tsx

Toggle in darkmode seemed to be having some faulty color values:
Fixes: -
2. Check in Components -> Toggle -> Web Component / Native
3. Check that the design for dark mode is correct.

fix(toggle): darkmode fixes

---

tegel/src/components/badge/badge.stories.tsx
tegel/src/components/badge/badges.tsx
tegel/src/components/badge/readme.md
tegel/src/stories/Migration/Migration.stories.mdx

Chagned badges isVisible prop to hidden. Also updated to migration docs.
Fixes: [AB#3260](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3260)
2. Check in Components -> Badge
3. Test the hidden controls.
4. Check the docs of the hidden props in the readme.
5. Check the migration docs update.

fix(badge): visibility prop

---

tegel/src/components/icon/readme.md
tegel/src/components/slider/readme.md
tegel/src/components/slider/slider.stories.tsx
tegel/src/components/slider/slider.tsx

Refactored the event name for the slider. Introduced a slider-id prop and cleaned up the story. Also moved some stuff around in the slider.tsx
Fixes: [AB#3360](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3360)
2. Check in Components -> Slider
3. Check the readme for the event
4. Check the log to make sure the event works as intended.

fix(slider): refactor event names

---

tegel/src/components/radio-button/radio-button-component.stories.tsx
tegel/src/components/radio-button/radio-button.tsx
tegel/src/components/radio-button/readme.md

Refactored event name to follow established conventions. Also refactored radio button label to adhere to the way it's implemented in checkbox web component.
Fixes: #
Go to storybook link below.
Check in Components -> Radio Button-> Web Component
Check the readme for the event specification.
Check the console for events being emitted on story.

fix(radio button): align event names

---

tegel/src/components/textfield/readme.md
tegel/src/components/textfield/textfield.stories.tsx
tegel/src/components/textfield/textfield.tsx

Renamed event names to conform with convention. Added events for all relevant event on the input element. Updated the story to log events as the are emitted.
Fixes: [AB#3363](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3363)
2. Check in Components -> Textfield
3. Check the readme for the event specification.
4. Check the console for events being emitted on story.

fix(textfield): refactored event names

---

tegel/src/components/textarea/readme.md
tegel/src/components/textarea/textarea.stories.tsx
tegel/src/components/textarea/textarea.tsx

Renamed event names to conform with convention. Added events for all relevant event on the input element. Removed unnecessary onClick event on the wrapping div. Updated the story to log events as the are emitted.
Fixes: [AB#3362](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3362)
2. Check in Components -> Textarea
3. Check the readme for the event specification.
4. Check the console for events being emitted on story.

fix(textarea): refactor event names

---

tegel/src/components/accordion/accordion-item/accordion-item.tsx
tegel/src/components/accordion/accordion-item/readme.md
tegel/src/components/accordion/accordion.stories.tsx

Changing event name to reflect "sdds + eventName" standard we settle upon. 
Fixes: [AB#3357](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3357)
1. Check the code and readme file, the event name needs to reflect "sdds + eventName" standard
2. In Storybook, inspect and see if in the console you get logging of events
This is an onClick event that does toggling so I was not 100% if this naming is OK. Let's see, no problem changing it to whatever is suggested in the review.

fix(accordion): events name update

---

tegel/src/components/badge/badge.stories.tsx

Standardised order of controls in Storybook for badge component.
Fixes: [AB#3424](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3424)
2. Check in Badge -> Default (and With Demo Component)

fix(badge): standardise order of controls in Storybook

---

tegel/src/components/accordion/accordion.stories.tsx

Standardised order of controls in Storybook for accordion component.
Fixes: [AB#3423](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3423)
2. Check in Accordion - Default
3. Inspect order on controls
4. Read descriptions of controls

fix(accordion): standardise order of Storybook controls

---

tegel/src/components/banner/banner.stories.tsx
tegel/src/components/banner/sdds-banner.stories.tsx

Describe pull-request
Updated control descriptions in Storybook for banner component.
Solving issue
Fixes: [AB#3425](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3425)
How to test
Add description how to test if possible
2. Check in Banner-> Native and Web Component

fix(banner): update control descriptions in Storybook

---

tegel/src/components/textarea/textarea-vars.scss

The textarea didn't have styling for different mode variants
Fixes: [AB#3475](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3475)
1. Go to storybook and open textarea component
2. disable component and test different mode variants.
Color from Figma:
Background:
Light primary: grey-50
Light Secondary: white
Dark primary: grey-900
Dark primary: grey-868
Placeholder:
Light primary + secondary: grey-400
Dark primary + secondary: grey-800
label:
Light primary + secondary: grey-400
Dark primary + secondary: grey-700

fix(textarea): correct disabled styling

---

components/src/components/textarea/readme.md
components/src/components/textarea/textarea.scss
components/src/components/textarea/textarea.tsx
tegel/src/components/textarea/readme.md
tegel/src/components/textarea/textarea.scss
tegel/src/components/textarea/textarea.stories.tsx
tegel/src/components/textarea/textarea.tsx

Added a prop for nominwidth for the textarea.
Fixes: #855
1. Check out branch and run storybook for components
2. Add nom nominwidth prop to textarea and check that the min-width is unset.

feat(textarea): added prop for no minwidth

---

tegel/src/components/button/button-native.stories.tsx
tegel/src/components/button/button-webcomponent.stories.tsx
tegel/src/components/button/button.scss

Standardised order of controls in Storybook for button component. Also updated descriptions and deprecated controls and fixed fullbleed bug in web component.
Fixes: [AB#3426](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3426)
**How to test** 
2. Check in Button -> Web Component and Native (and all sub stories)

fix(button): standardise order of controls in Storybook

---

tegel/src/components/checkbox/checkbox.stories.tsx
tegel/src/components/checkbox/sdds-checkbox.stories.tsx

Standardised order of controls in Storybook for checkbox component. Also updated descriptions and deprecated controls and added default values.
Fixes: [AB#3428](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3428)
2. Check in Checkbox-> Web Component and Native

fix(checkbox): standardise order of controls in Storybook

---

tegel/src/components/card/card.stories.tsx
tegel/src/components/card/sdds-card.scss
tegel/src/components/card/sdds-card.stories.tsx

Standardised order of controls in Storybook for card component. Also updated descriptions and made bodyImg control conditional on bodyDivider control to make it consistent.
Fixes: [AB#3427](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3427)
2. Check in Card-> Web Component and Native

fix(card): standardise order of controls in Storybook

---

tegel/package-lock.json
tegel/package.json
tegel/stencil.config.ts

https://github.com/scania-digital-design-system/sdds/tree/fix/toast-role-renaming
Upgrades to stencil 3 and added experimentalImportInjection.  experimentalImportInjection flag is needed for bundlers such as vite to lazily load our components. 
Fixes: -
1. Go to checkout branch
2. Run a build as check the terminal for errors.

build(stencil): upgrades to stencil 3

---

tegel/src/components/datetime/datetime.stories.tsx
tegel/src/components/datetime/datetime.tsx
tegel/src/components/datetime/readme.md

Events name update
Fixes: [AB#3358](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3358)
1. Go to the Netlify Storybook link
2. Check if events are firing on click/focus/blur 
3. Check if code looks OK
Work-related to ShadowDOM and some more improvements of this component I will do it in another PR. To keep PR slim and easy to review. I suggest going over commits to easily follow up what was happening.

fix(datetime): event name update

---

tegel/src/components/datetime/datetime.stories.tsx
tegel/src/components/footer/webcomponent/sdds-footer-link/readme.md

Standardised order of controls in Storybook for datetime component. Also updated descriptions, refactored noMinWidth control and remover unnecessary controls.
Fixes: [AB#3431](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3431)
2. Check in Datetime -> All sub stories

fix(datetime): standardise order of controls in Storybook

---

tegel/src/components/link/link.stories.tsx
tegel/src/components/link/sdds-link.stories.tsx

Standardised order of controls in Storybook for link component. Also updated descriptions and added default values to controls.
Fixes: [AB#3436](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3436)
2. Check in Link -> Web Component and Native

fix(link): standardise order of controls in Storybook

---

tegel/src/components/chips/chips.stories.tsx

Standardised order of controls in Storybook for chips component. Also updated descriptions and added default values.
Fixes: [AB#3429](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3429)
2. Check in Chips -> Native

fix(chips): standardise order of controls in Storybook

---

tegel/src/components/footer/footer.stories.tsx
tegel/src/components/footer/webcomponent/sdds-footer.stories.tsx

Updated control descriptions in footer Storybook file.
Fixes: [AB#3434](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3434)
2. Check in Footer -> Web Component and Native
3. inspect order of controls
4. Read control descriptions 

fix(footer): standardise order of controls in Storybook

---

tegel/src/components/message/message.scss
tegel/src/components/message/message.stories.tsx
tegel/src/components/message/sdds-message.stories.tsx

Standardised order of controls in Storybook for message component. Also updated descriptions and added default values to controls.
Fixes: [AB#3437](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3437)
2. Check in Message-> Web Component and Native

fix(message): standardise order of controls in Storybook

---

tegel/src/components/modal/modal-native.stories.tsx
tegel/src/components/modal/modal-webcomponent.stories.tsx

Standardised order of controls in Storybook for modal component. Also updated descriptions and added default values to controls.
Fixes: [AB#3438](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3438)
2. Check in Modal-> Web Component and Native

fix(modal): standardise order of controls in Storybook

---

tegel/src/components/slider/slider.stories.tsx

Standardised order of controls in Storybook for slider component. Also updated descriptions, added default values to controls and refactored deprecated conditional controls.
Fixes: [AB#3441](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3441)
2. Check in Slider -> Default

fix(slider): standardise order of controls in Storybook

---

tegel/src/components/button/button-webcomponent.stories.tsx

Seems we had double declaration of text prop in story
Fixes: No ticket, fixed bug on the fly.
1. Go to Storybook Link below
2. Make sure that no combination of props shows a double "text" attribute in the story demo code.

fix(button): double text prop in story

---

tegel/src/components/spinner/spinner.stories.tsx

Updated descriptions and added default values to controls for the spinner component.
Fixes: [AB#3442](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3442)
2. Check in Spinner-> Default and Inverted
3. Read control descriptions

fix(spinner): standardise order of controls in Storybook

---

tegel/src/components/popover-canvas/popover-canvas.stories.tsx
tegel/src/components/popover-menu/popover-menu-icons.stories.tsx
tegel/src/components/popover-menu/popover-menu.stories.tsx

Updated default values and descriptions in both popover canvas and popover menu components.
2. Check in Popover Canvas -> Default
3. Check in Popover Menu -> Default and With Icons

fix(popover): update default values in Storybook

---

tegel/src/components/radio-button/radio-button-component.stories.tsx
tegel/src/components/radio-button/radio-button.stories.tsx
tegel/src/components/radio-button/radio-button.tsx

Standardised order of controls in Storybook for radio button component. Also updated deprecated control, added default values and deconstructed args for consistency between stories.
Fixes: [AB#3439](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3439)
2. Check in Radio Button -> Web Component and Native

fix(radio button): standardise order of controls in Storybook

---

tegel/src/components/banner/sdds-banner.scss
tegel/src/global/global.scss

Add color var to button also to enable ligh/dark switch, and added vars to global.scss
Fixes: [AB#DTS-711](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-711)
2. Check in Components -> Banner, Web Component, see that the close button changes to white in light mode. 

fix(banner): correct color on close button in light mode

---

tegel/src/components/stepper/sdds-stepper.stories.ts
tegel/src/components/stepper/stepper.stories.tsx

Standardised order of controls in Storybook for stepper component. Also updated descriptions, added default values and refactored showLabel control in native component to match the web component structure.
Fixes: [AB#DTS-865](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-865)
2. Check in Stepper -> Native, Web Component and Web Component With Error

fix(stepper): standardise order of controls in Storybook

---

tegel/src/components/data-table/native-table.stories.tsx
tegel/src/components/data-table/table-component-basic.stories.tsx
tegel/src/components/data-table/table-component-batch-actions.stories.tsx
tegel/src/components/data-table/table-component-bodydata.stories.tsx
tegel/src/components/data-table/table-component-custom-width.stories.tsx
tegel/src/components/data-table/table-component-event-listeners.stories.tsx
tegel/src/components/data-table/table-component-expandable-rows.stories.tsx
tegel/src/components/data-table/table-component-filtering.stories.tsx
tegel/src/components/data-table/table-component-multiselect.stories.tsx
tegel/src/components/data-table/table-component-pagination.stories.tsx
tegel/src/components/data-table/table-component-sorting.stories.tsx

Standardised order of controls in Storybook for data table component. Also updated descriptions, refactored deprecated controls and introduced noMinWidth controls with custom width input to all sub-stories.
Fixes: [AB#DTS-708](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-708)
2. Check in Data Table -> All sub stories

fix(data table): standardise order of controls in Storybook

---

tegel/src/components/chips/chips.scss
tegel/src/components/chips/chips.stories.tsx

This is to increase the interoperability with react. Web component should not need to have classes on them. From what I could find this was the only place where we were adding a class to a <sdds-icon> komponent.
Fixes: -
Check that the component still behaves as expected.

fix(chip): removed class from sdds-icon

---

tegel/src/components/textarea/textarea-vars.scss
tegel/src/components/textarea/textarea.scss
tegel/src/components/textarea/textarea.tsx
tegel/src/components/textfield/textfield.scss
tegel/src/components/textfield/textfield.tsx
tegel/src/global/global.scss

Scoped css and removed class name creation in render method.
Fixes: -
2. Check in Components -> Textfield/Textarea
3. Check that the styling is still correct.

fix(textfield/textarea): scope css

---

components/src/components/modal/_modal-core.scss

Added a high z-index for the modal header in order for all elements that needs to scroll goes behind it.
Fixes: #525
1. Go to checkout branch
2. Run storybook for components
3. Add som elements to the scroll body and make sure the header scroll "above" all elements.

fix(modal): fix overflow/z-index issue within modal

---

tegel/src/components/dropdown/dropdown-vars.scss
tegel/src/components/dropdown/dropdown.scss
tegel/src/global/global.scss

Now uses the correct color when dropdown is disabled, also moves the inclusion of vars file to global css
Fixes: [DTS-712](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-712)
Go to storybook link below.
2. Check in Components -> Dropdown, Web Component, toggle disabled state and check that var(--sdds-grey-800) is being used.
[DTS-712]: https://tegel.atlassian.net/browse/DTS-712?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dropdown): correct color in disabled state

---

tegel/src/components/accordion/accordion.stories.tsx
tegel/src/components/badge/badge.stories.tsx
tegel/src/components/banner/sdds-banner.stories.tsx
tegel/src/components/button/button-webcomponent.stories.tsx
tegel/src/components/card/sdds-card.stories.tsx
tegel/src/components/data-table/table-component-basic.stories.tsx
tegel/src/components/data-table/table-component-batch-actions.stories.tsx
tegel/src/components/data-table/table-component-custom-width.stories.tsx
tegel/src/components/data-table/table-component-event-listeners.stories.tsx
tegel/src/components/data-table/table-component-expandable-rows.stories.tsx
tegel/src/components/data-table/table-component-filtering.stories.tsx
tegel/src/components/data-table/table-component-multiselect.stories.tsx
tegel/src/components/data-table/table-component-pagination.stories.tsx
tegel/src/components/data-table/table-component-sorting.stories.tsx
tegel/src/components/datetime/datetime.stories.tsx
tegel/src/components/footer/webcomponent/sdds-footer.stories.tsx
tegel/src/components/message/sdds-message.stories.tsx
tegel/src/components/modal/modal-webcomponent.stories.tsx
tegel/src/components/popover-canvas/popover-canvas.stories.tsx
tegel/src/components/popover-menu/popover-menu-icons.stories.tsx
tegel/src/components/popover-menu/popover-menu.stories.tsx
tegel/src/components/radio-button/radio-button-component.stories.tsx
tegel/src/components/slider/readme.md
tegel/src/components/slider/slider.stories.tsx
tegel/src/components/slider/slider.tsx
tegel/src/components/spinner/spinner.stories.tsx

Aligned all default values in Storybook with the corresponding props for web components. The few components that are not included in this PR either didn't need alignment or will be handled in their own standardisation on controls PR.
Fixes: [DTS-1023](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1023)
2. Check that the default values of the controls are the same as the default values in the notes in Storybook*
*If the default value in the notes is "null" or "undefined" (except for modeVariant which should always be "Inherit from parent") the control default value should be empty.
[DTS-1023]: https://tegel.atlassian.net/browse/DTS-1023?atlOrigin=eyJpIjoiNWRkNT …

fix: align default values to props

---

tegel/src/components/slider/readme.md
tegel/src/components/slider/slider.stories.tsx
tegel/src/components/slider/slider.tsx

Refactored control for scrubber size in slider component to better align with the corresponding prop.
Fixes: [DTS-1082](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1082)
2. Check in Slider -> Default
3. Check that the "Scrubber size" control changes the size of the scrubber
4. Check the "scrubberSize" default value in the Notes tab
[DTS-1082]: https://tegel.atlassian.net/browse/DTS-1082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(slider): refactor control for scrubber size

---

tegel/src/components/tabs/inline-tabs-default/inline-tabs.stories.tsx
tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.stories.tsx
tegel/src/components/tabs/navigation-tabs/navigation-tabs.stories.tsx

Standardised order of controls in Storybook for tabs component. Also updated descriptions and added default values.
Fixes: [DTS-866](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-866)
2. Check in Tabs -> Inline Tabs and Inline Tabs Fullbleed
[DTS-866]: https://tegel.atlassian.net/browse/DTS-866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(tabs): standardise order of controls in Storybook

---

tegel/src/components/textarea/textarea.stories.tsx

Standardised order of controls in Storybook for textarea component. Also updated descriptions, added default values and refactored noMinWidth control.
Fixes: [DTS-867](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-867)
2. Check in Textarea -> Default
[DTS-867]: https://tegel.atlassian.net/browse/DTS-867?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(textarea): standardise order of controls in Storybook

---

tegel/src/components/textfield/textfield.stories.tsx

Standardised order of controls in Storybook for textfield component. Also updated descriptions, added default values and refactored noMinWidth control.
Fixes: [DTS-868](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-868)
2. Check in Textfield -> Default
[DTS-868]: https://tegel.atlassian.net/browse/DTS-868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(textfield): standardise order of controls in Storybook

---

tegel/src/components/data-table/table-body-cell/table-body-cell.tsx
tegel/src/components/data-table/table-body-row-expandable/readme.md
tegel/src/components/data-table/table-body-row-expandable/table-body-row-expandable.tsx
tegel/src/components/data-table/table-body-row/readme.md
tegel/src/components/data-table/table-body-row/table-body-row.tsx
tegel/src/components/data-table/table-body/readme.md
tegel/src/components/data-table/table-body/table-body.tsx
tegel/src/components/data-table/table-component-event-listeners.stories.tsx
tegel/src/components/data-table/table-footer/readme.md
tegel/src/components/data-table/table-footer/table-footer.tsx
tegel/src/components/data-table/table-header-cell/readme.md
tegel/src/components/data-table/table-header-cell/table-header-cell.tsx
tegel/src/components/data-table/table-header/readme.md
tegel/src/components/data-table/table-header/table-header.tsx
tegel/src/components/data-table/table-toolbar/readme.md
tegel/src/components/data-table/table-toolbar/table-toolbar.tsx
tegel/src/components/data-table/table/readme.md
tegel/src/components/data-table/table/table.tsx

Refactored event names and updated story. 
Fixes: [AB#3361](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3361)
2. Check in Components -> Data Table -> Check all web component stories
3. Check the readme and event names to make sure they conform with convention.
4. Check if there are any events that are marked as internal now that should be external, and vice versa.
5. Check the event names. Since some event are so specific to this component I had to digress a bit from the naming convention.. 😢 

fix(table): refactor event names

---

tegel/src/components/accordion/accordion.tsx
tegel/src/components/accordion/readme.md

Removed unused divider prop.
Fixes: [DTS-1043](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1043)
2. Check in Accordion -> Default
3. Check that 'divider' is not present in Notes tab
[DTS-1043]: https://tegel.atlassian.net/browse/DTS-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(accordion): remove unused divider prop

---

tegel/src/components/divider/divider.stories.tsx

Standardised order of controls in Storybook for divider component. Also updated descriptions, removed unnecessary default value and renamed Default story to Native.
Fixes: [DTS-859](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-859)
2. Check in Divider-> Native and Border
[DTS-859]: https://tegel.atlassian.net/browse/DTS-859?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(divider): standardise order of controls in Storybook

---

tegel/src/components/header/header-all.stories.tsx
tegel/src/components/header/header-default.stories.tsx
tegel/src/components/header/header-inline.stories.tsx
tegel/src/components/header/header-search.stories.tsx
tegel/src/components/header/header-toolbar.stories.tsx

Updated control descriptions- and refactored deprecated controls.
Fixes: [DTS-861](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-861)
2. Check in Header -> All sub-stories
3. Read control descriptions
4. Check that "Site name" control works as it should
[DTS-861]: https://tegel.atlassian.net/browse/DTS-861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(header): standardise order of controls in Storybook

---

tegel/src/components/toast/sdds-toast.stories.tsx
tegel/src/components/toast/toast.stories.tsx

Standardised order of controls in Storybook for toast component. Also updated descriptions, added control spec and removed unnecessary if-statement.
Fixes: [DTS-869](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-869)
2. Check in Toast -> Native and Web Component
[DTS-869]: https://tegel.atlassian.net/browse/DTS-869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(toast): standardise order of controls in Storybook

---

tegel/src/components/toggle/sdds-toggle.stories.tsx
tegel/src/components/toggle/toggle.stories.tsx

Standardised order of controls in Storybook for toggle component. Also updated descriptions, removed unnecessary default value and aligned control options between native component and web component.
Fixes: [DTS-870](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-870)
2. Check in Toggle -> Native and Web Component
[DTS-870]: https://tegel.atlassian.net/browse/DTS-870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(toggle): standardise order of controls in Storybook

---

tegel/src/components/tooltip/tooltip.stories.tsx

Standardised order of controls in Storybook for tooltip component. Also updated descriptions, refactored deprecated controls and added default values.
Fixes: [DTS-871](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-871)
2. Check in Tooltip -> Web Component
[DTS-871]: https://tegel.atlassian.net/browse/DTS-871?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(tooltip): standardise order of controls in Storybook

---

components/src/components/textarea/textarea.scss
components/src/components/textarea/textarea.tsx
components/src/components/textfield/textfield.tsx

Added a error icon to the error state of the textarea. 
Also corrected previously commited error. The textarea was missing the function name for handleInput, which was causing the entire file to error.
Fixes: [#](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-703)
1. Go to checkout branch.
2. Run storybook for @components
3. Check that the textarea has a prefix error icon on helper in error state.
4. Check that the textarea works as expected.

fix(DTS-703): textarea error state icon

---

tegel/src/components/toggle/sdds-toggle.stories.tsx
tegel/src/components/toggle/sdds-toggle.tsx

Added a name to the default slot to make it handle dynamic data.
Fixes: -
2. Check in Components -> Toggle -> Web Component
3. Check that everything is still working as expected.

fix(sdds-toggle): added a name to the default slot

---

tegel/package-lock.json
tegel/package.json

Bumped npm version of new tegel

chore: release 0.0.5

---

tegel/src/components/slider/readme.md
tegel/src/components/slider/slider.tsx

The slider was crashing due to old null values getting checked. This removes these null checks and simply checks the true/false state of the prop.
The slider was crashing due to old null values getting checked. This removes these null checks and simply checks the true/false state of the prop.
Fixes: -
2. Check in Components -> Slider
3. Check that the controls work as inteded.

fix(slider): removing old null checks

---

tegel/src/components/stepper/sdds-stepper.stories.ts
tegel/src/components/stepper/stepper-item/sdds-stepper-item.tsx

Replaced default slot with named slot, not sure if number is a great name so please provide alternatives if you have any.
Fixes: -
2. Check in Componets -> Stepper -> Web Component
3. Check that everything still works as intended.

fix(stepper): added a name to the default slot

---

tegel/src/components/breadcrumb/sdds-breadcrumb-link/sdds-breadcrumb-link.scss
tegel/src/components/breadcrumb/sdds-breadcrumb-link/sdds-breadcrumb-link.tsx
tegel/src/components/breadcrumb/sdds-breadcrumb.stories.tsx

Replaced default slot with named.
Fixes: -
2. Check in Components -> Breadcrumb -> Web Component
3. Check that it still works as inteded.

fix(breadcrumb): removed default slot 

---

tegel/src/components/banner/sdds-banner.tsx
tegel/src/components/footer/webcomponent/sdds-footer-link/readme.md
tegel/src/components/footer/webcomponent/sdds-footer-link/sdds-footer-link.tsx
tegel/src/components/footer/webcomponent/sdds-footer.stories.tsx

The banner was using the old link prop (link-href) which was breaking it. And the footer-group-links was using the old link- prefix.
Fixes: -
2. Check in Components -> Banner -> Web Components
3. Check that the link opens a new page
4. To the same for footer links (web component)

fix(banner & footer): update link prop

---

tegel/src/components/stepper/sdds-stepper.stories.ts
tegel/src/components/stepper/stepper.scss

Added the correct border styling for inactive step in dark mode. 
Fixes: https://tegel.atlassian.net/browse/DTS-1269
2. Check in Components -> Stepper -> Native
3. Check that the styling is correct in both modes.

fix(stepper): added correct border styling on native label in dark mode

---

tegel/src/components/button/button-vars.scss

Added the correct color for native, focused secondary button with icon.
Fixes: [ #DTS-](https://tegel.atlassian.net/browse/DTS-1254)
2. Check in Components -> Button -> Native With Icon
3. Check the focused state of the secondary type.

fix(button): added correct color to focused button with icon in darkmode

---

tegel/src/components/dropdown/dropdown-vars.scss

Corrected the disabled backgound color variable for the web component dropdown.
Fixes: [DTS-1264](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1264)
2. Check in Dropdown -> Web Component Default
3. Set class sdds-mode-light to wrapping div
4. Check the styling for light/dark mode
[DTS-1264]: https://tegel.atlassian.net/browse/DTS-1264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dropdown): correct disabled background color vars

---

tegel/src/components/button/button-vars.scss

Describe pull-request
Added the correct color for focused state of secondary button
Solving issue
Fixes: [#DTS-](https://tegel.atlassian.net/browse/DTS-1250)
How to test
Go to storybook link below.
Check in Components -> Button -> Webcomponent
Check the focused state of the secondary type.
1. Go to...
2. Check in...
3. Run ...

fix(button): correct color to secondary in focused state

---

tegel/src/components/banner/readme.md
tegel/src/components/banner/sdds-banner.scss
tegel/src/components/banner/sdds-banner.stories.tsx
tegel/src/components/banner/sdds-banner.tsx
tegel/src/components/link/readme.md

Aligned how banner handles link and subheader with toast. Removed all the props and introduces two slots instead.
Fixes: [#DTS](https://tegel.atlassian.net/browse/DTS-1343)
2. Check in Components -> Banner -> Web Component
3. Check the styles for the link and subheader.
This does not solve the issue of the link having a different color than it's default in dark mode. 

feat(banner): aligned banner with toast on slots vs props

---

sandbox/react/src/App.js
sandbox/react/src/components/dataTable/dataTable.js
sandbox/react/src/components/header/Header.js

Testing data-table component responsive feature in React sandbox
There was a question from a user in the Development channel.
**Good to know**
- Separate page  was created to make tests for data table
- there are two different commits on how to deal with the responsiveness of data-table, please take a look on them
- this code relies on using the latest "@scania/components"

chore(react-sandbox): responsive data table example

---

tegel/src/components/header/header-vars.scss
tegel/src/components/header/header.scss

Checking color values for light and dark modes of header.
*Solving issue**  
Fixes: DTS-718
1. Check the open state of the App Launcher icon, it should be white background and dark tots on it.
2. Check mobile version of Avatar/Profil dropdown - it needs to have the same background color in regular and hover state as the rest of the items mobile menu.
3. Border/Vertical divider between header items is updated to reflect the value in Figma (grey 700 instead of grey 800)

fix(header): dark/light mode colors regression

---

tegel/src/global/global.scss

It makes sense that if we change the text to darkmode we would also change the default background so the text is not invisible.
This PR addresses that
**How to test** 
Clone the branch, add a .sdds-mode-dark somewhere, and see the background change!
Optionally test it more or less thoroughly.

fix: set default mode variant color and bgcolor

---

tegel/src/components/checkbox/checkbox-vars.scss
tegel/src/components/checkbox/checkbox.scss
tegel/src/components/checkbox/sdds-checkbox.scss

Corrected color and opacity for focused and hover states for checkbox ::before pseudo element in dark mode. Introduced variables for opacity to cater to the different opacity values in light vs dark mode. Also corrected the border-radius of the ::before element.
Fixes: [DTS-1251](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1251)
2. Check in Checkbox -> Native and Web Component
3. Put component in focused and hover states respectively
4. Compare styling to Figma
[DTS-1251]: https://tegel.atlassian.net/browse/DTS-1251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(checkbox): correct color for focused and hover states

---

tegel/src/components/stepper/sdds-stepper.scss

Updates the gap between steps on the vertical stepper. 
Fixes: [DTS-1265](https://tegel.atlassian.net/browse/DTS-1265)
Go to storybook link below.
Check in Components -> Stepper -> Webcomponent
Change to the Vertical version. Check that the distance is 52px
[DTS-1265]: https://tegel.atlassian.net/browse/DTS-1265?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(stepper): update stepper gap in vertical

---

tegel/src/components/header/header-vars.scss
tegel/src/components/header/header.scss

Correct color for close icons header part. 
Fixes: [#](https://tegel.atlassian.net/browse/DTS-1394)
1.Go to Storybook link below
2. Check in Header -> Inline Menu, switch to dark mode
Resize the window so the menu items are moved into the side menu
Open the menu and see that the color is the same as Figma.
**Screenshots** 
Should look like this below.

fix(sider-menu): correct color on header in side menu dark mode

---

tegel/src/components/header/header-all.stories.tsx
tegel/src/components/header/header-vars.scss
tegel/src/components/header/header.scss
tegel/src/components/side-menu/side-menu-vars.scss
tegel/src/components/side-menu/side-menu.scss
tegel/src/components/side-menu/side-menu.stories.tsx

Implemented a selected state background color for selected menu items in the headers side menu. Previously there was only a hover state background color in mobile view, where the side menu is visible. 
Fixes: [DTS-1393](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1393)
2. Check in Header -> All Menus
3. Resize the window so the menu items are moved into the side menu
4. Open the side menu and inspect the selected menu item
5. Check in both light and dark mode and compare with Figma
[DTS-1393]: https://tegel.atlassian.net/browse/DTS-1393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(side menu): selected state background color for header side menu

---

components/src/components/modal/modal.tsx

If the user used the modal methods to contol the open/closed state of the modal it would render an error in the console where we did a querySelectAll() - with an empty argument. This PR adds a simple null check to avoid this.
Fixes: #975
1. Check out branch.
2. Check in Components -> Modal
3. Remove the selector from one of the modal and open it with it's class method.
4. Check that there are no errors in the console.

fix(modal): added null check to avoid empty selector

---

tegel/src/components/link/link-vars.scss
tegel/src/components/link/link.scss
tegel/src/components/link/sdds-link.scss
tegel/src/global/global.scss

Updating link states colors
Fixes: DTS-1244
1. Check if active/focused/visited/disabled/hover are as in Figma in both light and dark mode

fix(link): colors update

---

tegel/src/components/accordion/accordion-item/accordion-item.scss
tegel/src/components/accordion/accordion-vars.scss

Updating color values after regression on dark/light mode
Fixes: DTS-1234
Check these statements: 
1. The chevron is currently grey-958 in light mode, should be black.
2. In dark mode text and chevron are white, should be grey 50. 

fix(accordion): dark/light regression color update

---

components/src/components.d.ts
components/src/components/dropdown/dropdown-filter.tsx
components/src/components/dropdown/dropdown.stories.js
components/src/components/modal/readme.md

Adds a open-direction prop to the dropdown-filter.
Fixes: https://tegel.atlassian.net/browse/DTS-1409
1. Check out the branch and run storybook.
2. Check in Components -> Dropdown -> Filter
3. Try the open direction controls.

feat(dropdown-filter): open direction prop

---

tegel/src/components/accordion/accordion-item/accordion-item.tsx
tegel/src/components/accordion/accordion-item/readme.md
tegel/src/components/accordion/accordion.stories.tsx

This PR enables for users to cancel the sddsToggle event that is emitted whenever a accordion-item is toggled. It also adds a public method for the users to trigger the event with. Lastly I added a "accordion-item-header" slot that can be used instead of the 'header' prop currently on the component.
Fixes: [DTS-1083](https://tegel.atlassian.net/browse/DTS-1083)
2. Check in Components -> Accordion
3. Check the readme for the event and the public method.
4. Check out the branch
5. Try preventing an event
6. See it fail to execute
[DTS-1083]: https://tegel.atlassian.net/browse/DTS-1083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …

feat(accordion): cancelable events

---

tegel/src/components/toast/sdds-toast.stories.tsx
tegel/src/components/toast/sdds-toast.tsx

Cleaned up the emitting of close event for toast. Logged the entire event object in storybook.
Fixes: https://tegel.atlassian.net/browse/DTS-1112
2. Check in Components -> Toast -> Web Component
3. Check the log for the event object when closed.
4. Check out the branch and try to prevent the event.
5. See it fail to execute.

feat(toast): cancelable event

---

tegel/src/components/accordion/accordion-item/readme.md
tegel/src/components/radio-button/radio-button-component.stories.tsx
tegel/src/components/radio-button/radio-button.tsx

Marked change event as non-cancelable added handleChange method to emit event.
Fixes: https://tegel.atlassian.net/browse/DTS-1104
2. Check in Components -> Radio Button -> Web Component
3. Check the event that's being emitted in the console.

fix(radio-button): cancelable events

---

tegel/src/components/modal/modal.tsx

Make sure the modal follows the acceptance criteria for cancellable events. Also removed the stopPropagation(), by doing so we allow for events to bubble up the DOM tree. 
Fixes: [DTS-1101](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1101&text=Modal)
1. Go to...
2. Check in...
3. Run ...
Question, should we have a ```sddsShow/open```event also? Something like this:
`@Event({
eventName: 'sddsOpen',
composed: true,
cancelable: true,
bubbles: true,
})
sddsOpen: EventEmitter<any>;`
To be called on from ```handleShow```, like this:
`handleShow = () => {
this.isShown = true;
this.sddsOpen.emit();
};`
Will create a ticket for …

feat(modal): allow propagation up the DOM tree

---

tegel/src/components/button/button.scss
tegel/src/components/toast/readme.md

The current implementation of the button makes it fill its parent, this fixes that.
Fixes: [DTS-1458](https://tegel.atlassian.net/browse/DTS-1458)
1. Go to Storybook
2. Check in Button webcomponent, inspect it and make sure it does not take the whole widht.
[DTS-1458]: https://tegel.atlassian.net/browse/DTS-1458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(button): button should not fill its parent

---

tegel/src/components/slider/slider.stories.tsx
tegel/src/components/slider/slider.tsx

Set cancelable: false for non cancelable events. 
Fixes: [DTS-1106](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1106)
2. Check in Slider -> Default
3. Change the value on the slider
4. Check that the logged event has cancelable: false
[DTS-1106]: https://tegel.atlassian.net/browse/DTS-1106?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(slider): set change event to not be cancelable

---

tegel/src/components/dropdown/dropdown-filter/dropdown-filter.tsx
tegel/src/components/dropdown/dropdown.tsx
tegel/src/components/dropdown/readme.md

Marked non-cancelable event as cancelable false, update event name.
Fixes: https://tegel.atlassian.net/browse/DTS-1095
2. Check in Components -> Dropdown -> Web Components and the filter version
3. Check that it still works as expected.

fix(dropdown): cancelable events

---

tegel/src/components/data-table/table-body-row-expandable/table-body-row-expandable.tsx
tegel/src/components/data-table/table-body-row/table-body-row.tsx
tegel/src/components/data-table/table-body/table-body.tsx
tegel/src/components/data-table/table-footer/table-footer.tsx
tegel/src/components/data-table/table-header-cell/table-header-cell.tsx
tegel/src/components/data-table/table-header/table-header.tsx
tegel/src/components/data-table/table-toolbar/table-toolbar.tsx
tegel/src/components/data-table/table/table.tsx

Made all events non-cancelable in the data-table. If the user want to implement their own logic for certain events there are props in place for that. See: enable-client-pagination.
Fixes: https://tegel.atlassian.net/browse/DTS-1092

fix(data-table): made all events non-cancelable

---

tegel/src/components/dropdown/dropdown.scss

Refactored SCSS rule to properly implement and display the color variable for when the "Label position" is set to "Outside".
Fixes: [DTS-1474](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1474)
2. Check in Dropdown -> Web Component Default, Web Component Multiselect
3. Check in Dropdown Filter -> Default
4. Set "Label position" to "Outside"
5. Check that the label is visible in both light and dark mode.
[DTS-1474]: https://tegel.atlassian.net/browse/DTS-1474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(dropdown): refactor scss rule to display label-outside color

---

tegel/src/components/slider/slider.scss

Added correct border-radius to input field wrapper.
Fixes: https://tegel.atlassian.net/browse/DTS-1312
2. Check in Components -> Slider
3. Add the input field.
4. Check the top left and right border-radius on the input field.

fix(slider): input field border radius

---

tegel/src/utils/utils.ts

Adds a utils method for appending a hidden input for form elements. This can be used by our own input element that needs has a shadowDOM.
Fixes: #

feat(utils): appendHiddenInput

---

tegel/src/components/tabs/folder-tabs/folder-tabs.stories.tsx
tegel/src/components/tabs/folder-tabs/folder-tabs.tsx
tegel/src/components/tabs/inline-tabs/inline-tabs.stories.tsx
tegel/src/components/tabs/inline-tabs/inline-tabs.tsx
tegel/src/components/tabs/navigation-tabs/navigation-tabs.stories.tsx
tegel/src/components/tabs/navigation-tabs/navigation-tabs.tsx

Enabled events to be cancelable, made internal variables private, removed watcher and logged entire event object in Storybook.
Fixes: [DTS-1109](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1109)
2.  Check in Components -> Tabs -> All sub stories.
3. Check the log for the event object when switching tabs.
4. Check out the branch and try to prevent the event.
5. See it fail to execute.
[DTS-1109]: https://tegel.atlassian.net/browse/DTS-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(tabs): cancelable events

---

tegel/src/components/data-table/data-table-vars.scss
tegel/src/global/global.scss

This PR enables light mode by default.
Fixes: https://tegel.atlassian.net/browse/DTS-1477
2. Check in Components -> Data-table -> WC
3. Check that primary vs secondary is correct.
4. Check the "root" of the HTML.
5. See that it has the correct bg and color based on theme.

fix(global): bg and color - default to light mode

---

tegel/src/components/slider/slider.scss
tegel/src/components/slider/slider.tsx

Refactored the label position in the slider component to adhere to the design in Figma.
Fixes: [DTS-1309](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1309)
1. Go to Storybook link below.
2. Check in Components -> Slider -> Default
3. Set "Show label" to true
4. Try out the controls
- Show ticks
- Show tick numbers
- Show controls
- Show value input field
5. Compare label position to design in Figma
[DTS-1309]: https://tegel.atlassian.net/browse/DTS-1309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(slider): refactor slider label position

---

tegel/src/components/datetime/datetime.scss
tegel/src/components/datetime/datetime.tsx

Removed shadowDOM on the datetime to allow it to work within a form. Had to unset the background on the wrapping element with the class `sdds-form-datetime` to not have its background being set by our global styling.
Fixes: https://tegel.atlassian.net/browse/DTS-1462
1. Go to Components -> Datetime
2. Check that the styling is still correct for all the variants.

feat(datetime): removed shadowDOM

---

tegel/src/components/stepper/readme.md
tegel/src/components/stepper/sdds-stepper.scss
tegel/src/components/stepper/sdds-stepper.stories.ts
tegel/src/components/stepper/sdds-stepper.tsx
tegel/src/components/stepper/stepper-item/readme.md
tegel/src/components/stepper/stepper-item/sdds-stepper-item.scss
tegel/src/components/stepper/stepper-item/sdds-stepper-item.tsx

This PR does a few things:
* The sdds-stepper emits a `internalSddsPropsChange` event when one of its props have changes.
* The stepper children (sdds-stepper-item) listens for a `internalSddsPropsChange` and updates if their parent has had changes.
* I removed the setting of widths of child components via JS and instead to it with CSS. This should hinder any flickering of the width of the stepper children. 
Fixes: https://tegel.atlassian.net/browse/DTS-1266
2. Check in Components -> Stepper -> Web Component
3. Check that the styling is correct. 

fix(stepper): propagate prop updates & CSS changes

---

components/src/components/slider/slider.tsx
tegel/src/components/slider/readme.md
tegel/src/components/slider/slider.stories.tsx
tegel/src/components/slider/slider.tsx

Fixing issue reported in Development support.
A slider with "Snap to ticks" enabled and "Show ticks" ends up with an undefined value if the mouse is pulled way to the right of the slider. Check the main branch and compare it with this PR.
Fixes: DTS-1551
1. Open the link for PR
2. Check the Slider component
3. Make sure to have "Show ticks" and "Snap to ticks"
4. Drag the mouse to the far right, the value needs to remain on the max value, not going to undefined.
5. To see the issue, check the main branch and test it.
1. Fix is done for both @scania/tegel and @scania/components
2. There is another bug discovered with keyboard left/right arrows and "Show ticks" and "Snap to …

fix(slider): snap to ticks & undefined

---

tegel/src/components/dropdown/dropdown-native.stories.tsx
tegel/src/components/header/webcomponent/header-item/readme.md
tegel/src/components/radio-button/radio-button-component.stories.tsx
tegel/src/components/radio-button/radio-button.stories.tsx
tegel/src/components/toggle/sdds-toggle.stories.tsx
tegel/src/components/toggle/toggle.stories.tsx

Changed the sb controls that are controlling label text from "Label" to "Label text". Many components already had this. I did it to be more consistent and avoid mistakes in refactoring Figma
1. Check effected components sb.

fix: changed sb ctrl from "label" to "label text"

---

tegel/src/components/header/webcomponent/header-brand-symbol/header-brand-symbol.scss
tegel/src/components/header/webcomponent/header-title/header-title.scss
tegel/src/patterns-stories/navigation/navigation-fewitems.stories.tsx
tegel/src/patterns-stories/navigation/navigation-manyitems.stories.tsx
tegel/src/patterns-stories/navigation/navigation-user-menu.stories.tsx

Makes the header go to "mobile-version" at 992px (large). And adds a ellipsis to the header title if it overflows.
Based on design: https://www.figma.com/file/hoi8RrFUaqRw28rvHa4KJX/Header-exploration?node-id=512-145824&t=We39OFEaFjBjOJ8C-0
Fixes: https://tegel.atlassian.net/browse/DTS-1543
2. Check in Patterna -> Navigation -> Few Navigation Items
3. Make the screen smaller.
4. Check the header-title.

fix(header-title): added overflow:hidden

---

tegel/src/components/data-table/table-body-cell/table-body-cell.tsx
tegel/src/components/data-table/table-body/readme.md
tegel/src/components/data-table/table-body/table-body.tsx
tegel/src/components/data-table/table-component-event-listeners.stories.tsx
tegel/src/components/data-table/table-component-filtering.stories.tsx
tegel/src/components/data-table/table-component-pagination.stories.tsx
tegel/src/components/data-table/table-component-sorting.stories.tsx
tegel/src/components/data-table/table-footer/readme.md
tegel/src/components/data-table/table-footer/table-footer.tsx
tegel/src/components/data-table/table-header-cell/readme.md
tegel/src/components/data-table/table-header-cell/table-header-cell.tsx
tegel/src/components/data-table/table-toolbar/readme.md
tegel/src/components/data-table/table-toolbar/table-toolbar.tsx
tegel/src/components/icon/readme.md
tegel/src/stories/Migration/Migration.stories.mdx

This PR refactors the events in the data-table. It also removes the following props: 
`disableFilteringFunction`, `disableSortingFunction` and `enableClientPagination`
It introduces the following events:  `sddsPageChange`, `sddsSortChange`, `sddsFilterChange`
These can be prevented by a user to achieve the same effect as the props above. 
This is more inline with how other components work.
Also added a section in the migration docs to outline the breaking changes.
Fixes: https://tegel.atlassian.net/browse/DTS-1479
2. Check in Data Table -> Web Components -> Sorting, Filtering, Pagination
3. Trigger the event for the corresponding story and look in to console for a log of the event. 
4. Check …

feat(data table): event refactoring and removal of props

---

tegel/src/components/side-menu/webcomponent/readme.md
tegel/src/components/side-menu/webcomponent/side-menu-collapse-button/readme.md
tegel/src/components/side-menu/webcomponent/side-menu-collapse-button/side-menu-collapse-button.scss
tegel/src/components/side-menu/webcomponent/side-menu-collapse-button/side-menu-collapse-button.tsx
tegel/src/components/side-menu/webcomponent/side-menu-dropdown-list-item/side-menu-dropdown-list-item.tsx
tegel/src/components/side-menu/webcomponent/side-menu-dropdown-list/side-menu-dropdown-list.tsx
tegel/src/components/side-menu/webcomponent/side-menu-dropdown/side-menu-dropdown.tsx
tegel/src/components/side-menu/webcomponent/side-menu-item/side-menu-item.tsx
tegel/src/components/side-menu/webcomponent/side-menu-webcomponent.stories.tsx
tegel/src/components/side-menu/webcomponent/side-menu.tsx

This PR makes the collapse event cancelable. To do this we emit one event 'sddsCollapse' that can be listened to and canceled by the user. If that event is not canceled we emit an 'internalSddsCollapse' that is listened to by other sdds-side-menu components. 
I also added a onClick event listener to the sdds-side-menu-collapse-button that handles the collapsing automatically if the users chooses to. If they want to control on their own they can cancel the event and toggle the collapased prop. The prop is being watched and emit the same 'internalSddsCollapse' event when it changes.
I also added a propschange event. But since this component only has one prop that is likely to change in runtime (collapsed) I didn't bother with any relevant props for now. I just …

feat(side-menu): make the collapse event cancelable

---

tegel/src/components/header/header-vars.scss
tegel/src/components/header/webcomponent/header-dropdown-list-item/header-dropdown-list-item.scss
tegel/src/components/header/webcomponent/header-hamburger/header-hamburger.scss
tegel/src/components/header/webcomponent/header-item/header-item-global.scss
tegel/src/components/header/webcomponent/header-item/header-item.scss
tegel/src/components/header/webcomponent/header-launcher-grid-item/header-launcher-grid-item.scss
tegel/src/components/side-menu/side-menu-vars.scss
tegel/src/components/side-menu/webcomponent/side-menu-dropdown-list-item/side-menu-dropdown-list-item.scss
tegel/src/components/side-menu/webcomponent/side-menu-dropdown/side-menu-dropdown.scss
tegel/src/components/side-menu/webcomponent/side-menu-item/side-menu-item.scss

Fixes darkmode color issues in header and sidemenu.
Fixes: #DTS-717

feat(header,side-menu): fix dark mode color issues

---

components/src/components/modal/_modal-core.scss

Increasing max height to 85vh for modal component
Fixes: DTS-1683
1. Check the Netlify link below OR branch out on your local
2. Choose a Modal component
3. Try to insert a lot of content
4. Modal should grow in height until it reaches 85% of the viewport height, after that scroll should show up

fix(modal): increasing max height to 85vh

---

components/readme.md

Content update on readme file for components package
Fixes:  DTS-1842
Content is updated long time ago but not reflected on the npm website of the package. I thought that maybe a change like this would trigger npm to frop cache on their side and update it accordion to new changes. 
1. Needs a release
I wrote an e-mail to npm support to see if they can do anything on their side too until we do a release.

docs(components-readme): test to drop cache on npm website

---

components/src/components.d.ts
components/src/components/datetime/datetime.stories.js
components/src/components/datetime/datetime.tsx
components/src/components/datetime/readme.md

Props to set min and max value of input
Fixes: DTS-2179
1. Go to Netlify preview link
2. Try to set different min/max values in Storybook.
3. Check if works as intended for date and datetime. "time" has issues with limitation even in native HTML component.
Example for different types: datetime="2023-01-31T00:00" date="2023-01-01" time="15:00"

feat(datetime): min & max props

---

components/src/components/dropdown/dropdown.tsx

The dropdown had a flicker/change in height when you were using the multiselect version. See video:
https://github.com/scania-digital-design-system/sdds/assets/62651103/e2c337d6-040a-4f2e-a3ec-7ea08578e756
This was due to faulty logic, we were checking if the dropdown had labelposition inside and selected value was not equal to '' OR if the selectedLabelsArray had no items in it. 
What we should check is:
if the labelposition was inside AND selected value was not equal to '' OR if the selectedLabelsArray had no items in it. 
Fixes: -
2. Check in dropdown -> multiselect
3. Check that it there is no flicker/size diff when selected/unselected.

fix(dropdown): faulty logic in label check was fixed

---

components/.storybook/preview.js
components/package-lock.json
components/package.json
components/readme.md
components/src/components/stories/deprecation.stories.js
icons/package-lock.json
icons/package.json
icons/readme.md
theme/core/colour/README.md
theme/core/colour/package-lock.json
theme/core/colour/package.json
theme/core/grid/README.md
theme/core/grid/package-lock.json
theme/core/grid/package.json
theme/core/typography/README.md
theme/core/typography/package-lock.json
theme/core/typography/package.json
theme/light/package-lock.json
theme/light/package.json
theme/light/readme.md

1. Deprecation message for SDDS packages
2. Bumping version of "patch" number for SDDS packages
3. Adding intro deprecation story to Storybook
Packages that will have deprecation message and patch version bumped:
- @scania/icons
- @scania/theme-light
- @scania/components
- @scania/grid
- @scania/colour
- @scania/tyography
Fixes: https://tegel.atlassian.net/browse/CDEP-2746
1. Check that all packages from the list have new deprecation message
2. Check that all packages from above have "patch" number bumped as preparation for release
3. Check if when loading Storybook, page initially loaded is deprecation notice story

docs: deprecation message for sdds packages
