scania-digital-design-system/sdds

theme/default/src/styles/core/grid/README.md
theme/default/src/styles/core/grid/compile.js
theme/default/src/styles/core/grid/package-lock.json
theme/default/src/styles/core/grid/package.json

New grid package containing css
Only css for now
Very simple feature
Fixes a part: scania/scania-theme#163
npm link package and try and use it
Try and use some of the grid classes

Feature - inital package for grid alpha

---

theme/light/src/styles/components/_badges.scss
theme/light/src/styles/components/_breadcrumbs.scss
theme/light/src/styles/components/_button.scss
theme/light/src/styles/components/_dropdowns.scss
theme/light/src/styles/components/_forms.scss
theme/light/src/styles/components/_pagination.scss
theme/light/src/styles/components/_progressbars.scss
theme/light/src/styles/components/_table.scss
theme/light/src/styles/core/grid/_breakpoints.scss
theme/light/src/styles/core/spacing/_vars.scss
theme/light/src/styles/core/spacing/spacing-vars.scss
theme/light/src/styles/patterns/c-content.scss
theme/light/src/styles/patterns/c-cookie.scss

Renamed all tokens based on the figma change
- Check all tokens name
- Check variables names

naming for all spacing tokens changed

---

components/package-lock.json
components/package.json
components/readme.md

- Bumped components and theme-light to 1.0.0-beta.0
- Fixed readme links
1. run npm build on components and theme-light

Bump version package and fix readme

---

theme/light/src/styles/core/colour/package-lock.json
theme/light/src/styles/core/typography/package-lock.json
theme/light/src/styles/core/typography/package.json

Update typograhpy package and color
Fixes: #

Update typograhpy package and color

---

readme.md

Fix table on readme

---

theme/light/src/styles/core/typography/_tokens.scss

- Incorrect values from the netlify branch in typography type-scales 
Look at the values + storybook typography headlines

bug - fix for type-scale value 

---

components/src/components/button/button.scss
components/src/components/button/button.stories.js
components/src/components/theme/theme.scss
components/src/components/theme/theme.tsx
theme/light/src/_mixins.scss
theme/light/src/components/_button.scss

Add buttons styling
Fixes: [AB#291](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/291)
- Check styling in Figma > UI Kit (Global) > Buttons
- Check different size and types in storybook options

AB#291 Feature- buttons

---

components/src/components/divider/divider.scss
components/src/components/divider/divider.stories.js
theme/light/src/components/_divider.scss
theme/light/src/patterns/c-theme.scss

Divider component 
**Based on textfield branch! Just review divider**
- One version of the component that takes a 1px width, based on width
- One version with height 1px and height: 100%, grows based on content height
- Border version
Fixes: [AB#301](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/301)
- run storybook
- View figma > global sdds > divider
_Add any other context about the …

AB#301 - Feature/divider component

---

components/src/components/accordion/accordion-item.tsx
components/src/components/accordion/accordion.scss
components/src/components/accordion/accordion.stories.js
components/src/components/accordion/accordion.tsx
components/src/components/accordion/readme.md
components/src/components/theme/theme.scss
components/stencil.config.ts
theme/light/src/components/_accordion.scss
theme/light/src/patterns/c-theme.scss

- Added styling to accordion
- Add it as web component
- It is also available as classes including expanded state
- Check Figma > UI Kit Global > Accordion
FIX for [AB#300](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/300)

AB#300 Add accordion styles

---

components/src/components/button/readme.md
components/src/components/dropdown/dropdown-option.tsx
components/src/components/dropdown/dropdown.scss
components/src/components/dropdown/dropdown.stories.js
components/src/components/dropdown/dropdown.tsx
components/src/components/dropdown/readme.md
components/src/components/link/link.scss
components/src/components/table/readme.md
theme/light/src/components/_dropdowns.scss
theme/light/src/patterns/c-theme.scss

- Added dropdown styling
- Added dropdown interaction
Fixes: [AB#474](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/474)
- Check Figma for styling guidelines
- Check if dropdown works in different browser
- Basic dropdown (not include different types)
NOT INCLUDED in this PR
-  Multi select
-  Filter
-  Nested

AB#474 Feature/dropdown

---

theme/core/package-lock.json
theme/core/package.json
theme/core/typography/_typography.scss
theme/core/typography/compile.js

Add fonts to typography package
Fixes: #25 [AB#475](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/475) 
- Use @scania/typography without theme & components
- See if the fonts is applied
Additional notes:
- See if we should remove fonts for c-theme ?

AB#475 Improvement - add scania fonts typography package

---

components/src/components/dropdown/dropdown-option.tsx
components/src/components/dropdown/dropdown.scss
components/src/components/dropdown/dropdown.stories.js
components/src/components/dropdown/dropdown.tsx
components/src/components/dropdown/readme.md
components/src/patterns/dropdown-filter/dropdown-filter.scss
components/src/patterns/dropdown-filter/dropdown-filter.tsx
components/src/patterns/dropdown-filter/readme.md
theme/light/src/components/_dropdowns.scss

- Added feature "Filter" on dropdown
- Added as a separate component `sdds-dropdown-filter`
- Add the options via `data` attribute which should be an array of objects (See storybook to see how use it in code)
Fixes: [AB#474](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/474)
- Click on storybook > Dropdown > Filter
- See Figma for UI
- Check if filtering works
- Might want to check if it is used in another framework (Angular or React example page)'
**Additional notes**
Merge #85 first

AB#474 Feature/dropdown filter

---

components/src/components/dropdown/dropdown.scss

- Dropdown is covered by code-snippet in site
- Add high z-index to make it visible over any other elements in page

Fix z-index for dropdown

---

theme/core/_prefix.scss
theme/core/colour/_colour.scss
theme/core/colour/_vars.scss
theme/core/grid/_mixins.scss
theme/core/typography/_typography.scss
theme/core/typography/compile.js
theme/light/src/components/_accordion.scss
theme/light/src/components/_breadcrumb.scss
theme/light/src/components/_button.scss
theme/light/src/components/_checkbox.scss
theme/light/src/components/_dropdowns.scss
theme/light/src/components/_link.scss
theme/light/src/components/_radio-button.scss
theme/light/src/components/_textfields.scss
theme/light/src/components/_toggle.scss
theme/light/src/patterns/c-dropdown.scss
theme/light/src/patterns/c-theme.scss

- Update prefix from .sdds to sdds
- Fix prefix in core packages
- Remove c-dropdown css in theme light
- Fix compiler import in typography
- Add prefix in theme-light
Fixes: #73  [AB#518](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/518)
- Run build on theme
- Use in storybook / angular
- See everything still works
- Check scss files prefix all changes
- ### Changing prefix in components will be on separate PR

AB#518 Improvement/change sdds prefix in theme

---

components/src/components/accordion/accordion.scss
components/src/components/breadcrumb/breadcrumb.scss
components/src/components/button/button.scss
components/src/components/checkbox/checkbox.scss
components/src/components/divider/divider.scss
components/src/components/dropdown/dropdown.scss
components/src/components/link/link.scss
components/src/components/radio-button/radio-button.scss
components/src/components/textfield/textfield.scss
components/src/components/toggle/toggle.scss
components/src/helpers/style-helpers.scss

- from .sdds to sdds
Fixes: #73  [AB#518](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/518) 
- Check in components
- Check storybook works

AB#518  Change prefix in components

---

components/src/components/textarea/textarea.stories.js
readme.md

- Fix c-theme changed to sdds-theme in textarea stories
- Improve docs on homepage readme
*How to test*
- Check in netlify > textarea
- Check readme in ./sdds

Fix docs & sdds-theme in textarea

---

components/src/components/tooltips/tooltip.scss

Z-index for tooltip
Tooltip now appears infront of the code example.

Hotfixed z-index for tooltip

---

readme.md

Added a link to show all packages at once in the org for npm
Click link
Should show all packages under scania org

update readme with npm link to org

---

demo/HTML/html.css

-- Just a hotfix blue-800 --> blue-900

Hotfix blue-800 --> blue-900

---

components/package-lock.json
components/package.json
theme/core/grid/package-lock.json
theme/core/grid/package.json
theme/light/package-lock.json
theme/light/package.json

- @scania/components@1.4.2
- @scania/grid@1.2.0
- @scania/theme-light@2.1.0
Fixes: [AB#729](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/729)

AB#719 Publish from sprint 6

---

components/package-lock.json
components/package.json
theme/light/package-lock.json
theme/light/package.json

- @scania/components@1.5.0
- @scania/theme-light@2.2.0
Released on npm https://www.npmjs.com/org/scania
Fixes:  [AB#758](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/758)

AB#758 Publish from sprint 7

---

components/src/components/dropdown/dropdown-option.tsx
components/src/components/dropdown/dropdown.tsx

Picking a option in the dropdown in a angular application cause a error in the console
- Changed from HTMLcollection object to childnodes array for the loop
Fixes: [AB#785](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/785)
You can see the same problem on the digitaldesign.scania.com picking a option
1. build and npm link components
2. Run angular demo pick an option in the dropdown
3. no error

AB#785 Bug - dropdown angular error trying to loop an object

---

components/package-lock.json
components/package.json
theme/core/typography/package-lock.json
theme/core/typography/package.json
theme/light/package-lock.json
theme/light/package.json

- @scania/components@1.5.1
- @scania/typography@1.1.1
- @scania/theme-light@2.2.1
Fixes: [AB#799](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/799) 

AB#799 Publish 1.5.1

---

components/src/components/accordion/accordion.stories.js
components/src/components/banner/banner.scss
components/src/components/banner/banner.stories.js
components/src/components/breadcrumb/breadcrumb.stories.js
components/src/components/button/button.stories.js
components/src/components/checkbox/checkbox.stories.js
components/src/components/dropdown/dropdown.stories.js
components/src/components/icon/icon.stories.js
components/src/components/link/link.stories.js
components/src/components/radio-button/radio-button.stories.js
components/src/components/textarea/textarea.stories.js
components/src/components/theme/colour.stories.js
components/src/components/theme/grid.stories.js
components/src/components/theme/spacing.stories.js
components/src/components/theme/theme.scss
components/src/components/theme/typography.stories.js
components/src/components/toast/toast.scss
components/src/components/toggle/toggle.stories.js
components/src/components/tooltips/tooltip.stories.js
components/src/patterns/dealer-header/dealer-header.stories.js
components/src/patterns/footer/footer.stories.js
components/src/patterns/header/header.stories.js
components/src/patterns/navigation/navigation.stories.js
theme/light/src/components/_banner.scss
theme/light/src/theme/sdds-theme.scss

- New component banner
- Removed some unused code
Fixes: [AB#831](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/831)
Visit storybook either locally or with this preview link below
- Try different states
- Try different options, without prefix, subheadline and so on
- Screen size
Demo has c-icon component to show a icon

Feature - Banner component styling

---

components/package-lock.json
components/package.json
readme.md
theme/core/icons/package-lock.json
theme/core/icons/package.json
theme/core/typography/package-lock.json
theme/core/typography/package.json
theme/light/package-lock.json
theme/light/package.json

- @scania/components@1.6.0
- @scania/icons@1.0.0
- @scania/typography@1.2.0
- @scania/theme-light@3.0.0
FIx [AB#830](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/830)

AB#830 Publish from sprint 9

---

components/package-lock.json
components/package.json
package.json
theme/light/package-lock.json
theme/light/package.json

Feature/publish sprint 10
Fixes: [AB#857](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/857)

Feature  - Release of sprint 10

---

components/package-lock.json
components/package.json
theme/light/package-lock.json
theme/light/package.json

- @scania/theme-light@3.1.1
Publish #154

Publish banner fix missing import

---

components/package-lock.json
components/package.json
theme/light/package-lock.json
theme/light/package.json

- @scania/components@1.7.2
- @scania/theme-light@3.1.2
Fix [AB#876](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/876)

AB#876 Publish from sprint 11

---

components/src/patterns/header/_navbar-toolbar-menu.scss
components/src/patterns/header/header.stories.js
theme/light/src/patterns/header.scss

- Add headline-07 for category title typography
- Add space on app-drawer medium screen
Fixes: #152 [AB#860](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/860)
See #152 for the list of things to be fixed

AB#860 Add fixes for header #152

---

components/package-lock.json
components/package.json
theme/light/package-lock.json
theme/light/package.json

- @scania/components@1.8.0
- @scania/theme-light@3.2.0
Fix [AB#920](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/920)

AB#920 Publish from Sprint 12

---

components/src/patterns/header/_navbar-brand.scss

Change typeface of application title to Scania Sans Headline
Fixes: #
1. Go to storybook --> pattern --> header
2. Check application title font-family

Changed application title type to Scania Sans Headline #946

---

components/package-lock.json
theme/core/icons/package-lock.json
theme/core/icons/package.json

Pre-release package of the icons
1. Go to storybook or go to npmjs search for scania/icons
2. check storybook icon component or install scania/icon package with the next tag

release next icons

---

components/src/components/accordion/accordion.stories.js
components/src/components/radio-button/radio-button.scss
components/src/components/theme/colour.stories.js
components/src/components/toast/toast.scss
components/src/patterns/footer/footer.scss
theme/core/colour/_tokens.scss
theme/light/src/_variables.scss
theme/light/src/components/_accordion.scss
theme/light/src/components/_banner.scss
theme/light/src/components/_breadcrumb.scss
theme/light/src/components/_button.scss
theme/light/src/components/_cards.scss
theme/light/src/components/_checkbox.scss
theme/light/src/components/_divider.scss
theme/light/src/components/_dropdowns.scss
theme/light/src/components/_link.scss
theme/light/src/components/_modal.scss
theme/light/src/components/_radio-button.scss
theme/light/src/components/_spinner.scss
theme/light/src/components/_textfields.scss
theme/light/src/components/_toast.scss
theme/light/src/components/_toggle.scss
theme/light/src/components/_tooltip.scss
theme/light/src/patterns/footer.scss
theme/light/src/patterns/header.scss
theme/light/src/patterns/side-menu.scss
theme/light/src/theme/sdds-theme.scss

Updated colours
Fixes: [AB#944](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/944)
1. Go to storybook preview 
2. Check in colours 
3. Check components with the new colours and compare with figma
There are some colours/state missing on some components, notes done already

Feature - Big updated colours

---

components/package-lock.json
components/package.json
theme/core/colour/package-lock.json
theme/core/colour/package.json
theme/core/icons/package-lock.json
theme/core/icons/package.json
theme/light/package-lock.json
theme/light/package.json

- @scania/components@1.10.0
- @scania/colour@2.0.0
- @scania/grid@2.0.0
- @scania/icons@1.1.0
- scania-theme-core@0.0.1
- @scania/typography@1.2.0
- @scania/theme-light@3.4.0
Fixes: #
1. Go to...
2. Check in...
3. Run ...

Improvement - update packages in demo

---

components/src/components/breadcrumb/breadcrumb.scss
components/src/components/breadcrumb/breadcrumb.stories.js
theme/light/src/components/_breadcrumb.scss

Breadcrumb fix colours, pointer and story having extra space
1. Go to storybook preview
2. Look at breadcrumb changes
More changes needed from the backlog

Improvement - Breadcrumb fix colours, pointer and story having extra space

---

components/src/components/button/button.scss
components/src/components/button/button.stories.js

update button component colours and some other small fixes

Improvement - Button colours for icons and some other small fixes

---

components/src/components/icon/icon.stories.js
theme/light/src/components/_button.scss
theme/light/src/theme/sdds-theme.scss

Add the colors for on white background for button 
Fixes: [AB#1024](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1024)
1. Go to the preview link in netlify
2. Check button
3. Change background to white and the theme to on-white theme in the top toolbar
4. Compare to figma 

Improvement - Update on white background states for button

---

components/.eslintignore
components/.eslintrc.json
components/src/components/accordion/accordion-item.tsx
components/src/components/card/card.tsx
components/src/components/modal/modal.tsx
components/src/components/textarea/textarea.tsx
components/src/components/textfield/textfield.tsx
components/src/components/theme/grid.stories.js
components/src/global.ts

Fixes: [AB#1052](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1052)
1. Travis is running ESlint command
2. Passing travis test

Improvement- enabling all eslint rules

---

components/package-lock.json
components/package.json
theme/light/package-lock.json
theme/light/package.json

- @scania/components@1.12.0
- @scania/colour@2.0.0
- @scania/grid@2.0.0
- @scania/icons@1.1.0
- scania-theme-core@0.0.1
- @scania/typography@1.2.0
- @scania/theme-light@3.6.0
Fixes: #
1. Go to...
2. Check in...
3. Run ...

Feature - Sprint 17 

---

.gitattributes

Solve bug with binary files on mac in gitattributes
1. Run master branch after this is merged

Solve issue with binary changes

---

components/src/patterns/header/_mixins.scss
components/src/patterns/header/_navbar-menu-item.scss
components/src/patterns/header/_navbar-toolbar-menu.scss
components/src/patterns/header/header.scss
components/src/patterns/header/header.stories.js
components/src/patterns/side-menu/side-menu.scss
components/src/patterns/side-menu/side-menu.stories.js

Fixing focus(tabbing) and issue with borders and "jumpy" content
<br/>
<br/>
Fixes: 
#[AB1083](https://dev.azure.com/scaniadigitaldesignsystem/SDDS/_workitems/edit/1083)
#[AB1086](https://dev.azure.com/scaniadigitaldesignsystem/SDDS/_workitems/edit/1086)
<br/>
<br/>
**How to test focus(tabbing) issue**  
1. Run Storybook
2. Select Header component
3. Try to tab through header menu - it should show an outline around entire elements now
<br/>
<br/>
**How to test "jumpy" content issue**
1. Hover over different header menu options to see if the move for 1px left/right
<br/>
<br/>
Short discussion DEVs + Alex
- introducing new classes vs updating customer
- UX when we code
- CSS simplification: one class name for header …

Header: focus/tabbing + border jumpy content fix

---

demo/angular/angular12/angular.json
demo/angular/angular12/src/app/app.component.spec.ts
demo/angular/angular12/src/app/app.component.ts
demo/angular/angular12/src/app/app.module.ts
demo/angular/angular12/src/environments/environment.prod.ts
demo/angular/angular12/src/environments/environment.ts
demo/angular/angular12/src/index.html
demo/angular/angular12/src/polyfills.ts
demo/angular/angular12/src/test.ts
demo/angular/angular12/tsconfig.app.json
demo/angular/angular12/tsconfig.json
demo/angular/angular12/tsconfig.spec.json
demo/angular/angular13/angular.json
demo/angular/angular13/src/app/app.component.spec.ts
demo/angular/angular13/src/app/app.component.ts
demo/angular/angular13/src/app/app.module.ts
demo/angular/angular13/src/environments/environment.prod.ts
demo/angular/angular13/src/environments/environment.ts
demo/angular/angular13/src/index.html
demo/angular/angular13/src/polyfills.ts
demo/angular/angular13/src/test.ts
demo/angular/angular13/tsconfig.app.json
demo/angular/angular13/tsconfig.json
demo/angular/angular13/tsconfig.spec.json
theme/light/package-lock.json

Just a prettier running over recently added angular files

Prettier in demo/angular

---

components/src/components/modal/modal.stories.js
components/src/components/modal/modal.tsx

Enabling modal component to be opened from multiple buttons
Fixes: #[1093](https://dev.azure.com/scaniadigitaldesignsystem/SDDS/_workitems/edit/1093)
1. Run Storybook
2. Open Modal component
3. Try to open same modal (modal one) from two different button - primary and secondary
- In Documentation: Advise using classes instead of ids in HTML 
- check the use of modal-dismiss (is it OK to use it in button)

Open modal with multiple buttons

---

components/src/components/theme/theme.scss
components/src/helpers/_utility-classes.scss

Making a basic set of utility classes
Fixes: #[AB1151](https://dev.azure.com/scaniadigitaldesignsystem/SDDS/_workitems/edit/1151)
1. Open utility classes file
2. Run local environment
3. Try to add one of the utility classes to a HTML component

Utility classes

---

components/src/components/dropdown/dropdown.scss
components/src/components/dropdown/dropdown.stories.js
components/src/patterns/header/header.stories.js
components/stencil.config.ts
demo/HTML/index.html
demo/HTML/package-lock.json
package.json

- Fix issue with dropdown showing the whole list when closing it with more the 7 items (scroll).
- Added better example with dropdown
- Fixed button icon in storybook
- Added more dropdowns in html example
Fixes: #233 
1. Go to storybook dropdown
2. Add more then 7 items
3. open and close, it will show correct way

fix bug dropdown 7 items and update examples

---

components/package-lock.json
components/package.json
theme/light/package-lock.json
theme/light/package.json

- @scania/components@1.15.0
- @scania/colour@2.0.1
- @scania/grid@2.0.1
- @scania/icons@1.1.1
- scania-theme-core@0.0.1
- @scania/typography@1.2.1
- @scania/theme-light@3.6.3

feature - release sprint 20

---

.github/PULL_REQUEST_TEMPLATE.md

Improving PR readme file
Adding more info on how to add tickets to PR

Update PULL_REQUEST_TEMPLATE file

---

components/src/components/textarea/textarea.scss
components/src/components/textfield/textfield.scss
package.json
theme/light/src/components/_textfields.scss

Fix for border-bottom color in textarea component
Fixes: [AB#983](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/983) 
FIX:#188 
1. Go to Stroybook
2. Open Textarea component
3. Black underline needs to show on hover

fix(textarea): border-bottom color

---

components/package-lock.json
components/package.json
theme/light/package-lock.json
theme/light/package.json

BREAKING CHANGE: New version
Fixes: [AB#1288](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1288)
1. Go to...
2. Check in...
3. Run ...

feat(release): commit containg the release package.json

---

LICENSE
components/LICENSE
readme.md

Updating the readme.md file in the root folder and license files with the new year
- Added some badges from shield.io, might want to add more in the future
- Readme with local dev instructions
- 
1. Go to readme.md file and read the new changes

docs(readme): update readme and copyright

---

theme/light/readme.md

Updated the readme and removing old documentation regarding CDN link in theme readme.md.
We no longer support CDN 
1. Go to readme in theme/light
2. Check

docs(readme): update readme for theme package, remove the cdn link

---

LICENSE
components/LICENSE
components/src/components/theme/fullpage.stories.js
components/src/patterns/footer/footer.stories.js
demo/HTML/index.html
demo/HTML/side-menu.html
demo/angular/angular13/src/app/components/footer/footer.component.html
demo/react/src/components/footer/Footer.js

Small update for copyright year
Fixes: #273 
1. Go to files that have been changed

fix(copyright year): fixing copyright year

---

components/package-lock.json
components/package.json
theme/core/colour/package.json
theme/core/grid/package.json
theme/core/icons/package.json
theme/core/typography/package.json
theme/light/package-lock.json
theme/light/package.json

chore(bump versions): bump versions
1. Package.json file update correct

chore(bump versions): bump versions

---

components/src/patterns/header/header.scss

CSS selector specificity
Header "*" caused issues on other components due to specificity
1. Check that Header stills looks OK
2. No other component is harmed - stays the same as before

fix(header): css selector specificity

---

components/package.json
theme/light/package.json

chore: version bump release 24

---

readme.md

clean up unused netlify flag on readme.md
removed unused netlify flag on readme.md

chore(readme): clean up unused netlify flag

---

components/src/components/dropdown/_dropdown-core.scss
components/src/components/dropdown/dropdown-filter.tsx
components/src/components/dropdown/dropdown-option.tsx
components/src/components/dropdown/dropdown-select.scss
components/src/components/dropdown/dropdown.scss
components/src/components/dropdown/dropdown.stories.js
components/src/components/dropdown/dropdown.tsx
components/src/components/dropdown/readme.md
components/src/components/dropdown/readme_filter.md
components/src/helpers/components-shared.scss
components/src/patterns/header/header.scss

Various fixes and improvements for Dropdown component
Fixes:
1. [AB#1675](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1675)
2. [AB#1673](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1673)
3. [AB#1358](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1358), #270 
4. [AB#1386](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1386), #297 
5. #304 
6. #284 
7. Propagate selected-value and selected-text on the top of the parent as attributes.
8. [AB#1669](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd77 …

fix(dropdown): various improvements

---

components/src/patterns/header/header.scss

Increasing CSS selector specificity by wrapping everything with .sdds-nav
Fixes: No issue reported, just an improvement.
1. Open Storybook
2. Check if Header component looks and behaves as in master based Storybook

fix(header): increase css specificity

---

components/src/components/dropdown/_dropdown-core.scss
components/src/components/dropdown/dropdown.scss
components/src/components/dropdown/dropdown.tsx
components/src/helpers/components-shared.scss
demo/angular/angular12/src/app/components/home/home.component.html

Fixes made during integration test
1. Go to Storybook
2. Check that the dropdown component looks and behaves as before

fix(dropdown): post integration improvements

---

components/package.json
theme/light/package.json

Release of code done in sprint 26-27

chore: release sprint 26-27

---

theme/light/src/old/patterns/c-cookie.scss
theme/light/src/old/patterns/c-table.scss

Removing imports that cause build to fail
The import that are removed were anyway missing files that were causing build-in theme-light to fail.
1. On main brunch, do npm run clean and then try to run npm i - it will fail
2. Do the same for this branch - it should pass.

fix: removing missing files import

---

components/src/helpers/_utility-classes.scss

- More utilities added 
- removed prefix variable
1. Make sure it builds
2. Check what classes have been added

feat(utilites): more utilities added

---

components/src/components/textarea/textarea.scss
components/src/components/textarea/textarea.stories.js
components/src/components/textfield/readme.md
components/src/components/textfield/textfield.scss
components/src/components/textfield/textfield.stories.js
components/src/components/textfield/textfield.tsx

Updated textarea and textfield with new functionality
Fixes: [AB#1381](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1381) and [AB#1781](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1781)
Go to the generated storybook link
1781: Go to textarea, use the controler for rows and test if the size changes as you change rows.
1381: Go to textfield, change the controler for min width. resize the demo-contianer with inline with and se if the field cna shrink.
**Link for test**
https://task-1381.d1g8v8mrkx992n.amplifyapp.com/

fix: textarea and textfield improvements

---

.github/workflows/azuredevops-issue.yml

Fixes: #
1. Go to...
2. Check in...
3. Run ...

docs: update azuredevops issue template

---

components/src/patterns/side-menu/side-menu.scss

Adjusted the width of the sidemenu from 256 to 288. changed a few colors
Fixes: [AB#1882](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1882) and [AB#1881](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1881)
open storybook via generated link. check sidemenu width and colors in accordance with tasks

fix(sidemenu): changed with and some colors

---

components/package-lock.json
components/package.json

Release of code done under sprint 30

chore: release sprint 30

---

components/src/components/textfield/textfield.scss
components/src/components/textfield/textfield.stories.js
components/src/components/textfield/textfield.tsx

Added option for small size
Fixes: [AB#1884](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1884)
Go to textfield in storybook and test the size option

fix: (textfield) added option for small size

---

components/package-lock.json
components/src/components/block/block.scss
components/src/components/block/block.stories.js
components/src/components/theme/theme.scss

Block component PR. I had issues with rebasing so it was easier to cherry-pick related commits and create a new clean branch.

feat: block component

---

components/package-lock.json
components/package.json
theme/light/package-lock.json
theme/light/package.json

chore: release 31

---

components/package-lock.json
components/package.json
components/src/components/table/table-header-cell.tsx
components/src/components/table/table.tsx
theme/light/package-lock.json
theme/light/package.json

Fix issue with filtering & sorting logic

fix(data-table): sorting & filtering logic

---

components/package-lock.json
components/package.json

Release of work done in sprint 35

Release 35

---

components/package-lock.json
components/package.json

Release of work done in sprint 36

chore: release 36

---

readme.md

Just a name change from SDDS to Tegel

docs: sdds to tegel name change

---

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.yaml

Change name from SDDS to Tegel

docs(feat-requets-temp): from sdds to tegel

---

components/readme.md
theme/core/colour/README.md
theme/core/grid/README.md
theme/core/icons/readme.md
theme/core/typography/README.md
theme/light/readme.md

Changing the name from SDDS to Tegel in the readme file of packages published in NPM.

docs: update readme of packages to tegel

---

components/src/components/badges/badges-component.tsx
components/src/components/badges/badges.scss
components/src/components/badges/badges.stories.js
components/src/components/badges/readme.md

Added a prop for small size (simple red dot without number) and one for visibility.
Github: [#265](https://github.com/scania-digital-design-system/sdds/issues/265)
Azure: [AB#1337](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1337)

Empty badge version

---

components/package-lock.json
components/package.json
theme/light/package-lock.json
theme/light/package.json

chore: release 39

---

components/src/components/badges/badges-component.tsx
components/src/components/badges/badges.scss
components/src/components/badges/badges.stories.js

Simplified the badges code, removing some States and adding a size prop to be more consistent with other components

refactor(badges): Simplified code and added size prop

---

components/src/components/header/header.scss
components/src/components/header/header.stories.js

Makes the searchbar collapse in to the side menu on lower breakpoints
Fixes: [AB#1733](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1733)
Check the storybook link (Header > Searchbar menu). go to a breakpoint below the threshold and test around.

feat(header): search-bar

---

components/src/components/dropdown/dropdown-filter.tsx
components/src/components/dropdown/dropdown-option.tsx
components/src/components/dropdown/dropdown.scss
components/src/components/dropdown/dropdown.stories.js
components/src/components/dropdown/dropdown.tsx
sandbox/HTML/index.html

A new multiselect variation of the dropdown component
[AB#506](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/506) Build component - Multiselect
1. Go to storybook and test functionality

feat(dropdown): new multiselect type

---

components/src/components/icon/icon.stories.js
components/src/components/modal/_modal-core.scss
components/src/components/modal/modal-native.scss
components/src/components/modal/modal.scss
components/src/components/modal/modal.stories.js
theme/light/src/components/_modal.scss
theme/light/src/theme/sdds-theme.scss

Super small PR moving Icons and modal from bottom of list in storybook 
Check storybook to see that Modal and Icons are in alphabetical order instead of bottom

fix: moving modal and icon in storybook, moving modal theming in component

---

components/src/components/slider/readme.md
components/src/components/slider/slider.stories.js
components/src/components/slider/slider.tsx
sandbox/angular/src/app/components/home/home.component.html

Added missing touchevents so Slider can be used on mobile.
Added a custom change event so it's programatically possible to listen to value updates.
Updared story to reflect the new eventemitter.
Fixes: 2248
Checkout the branch, check the eventlistener (it will output to console). Put chrome in mobile mode and use the slider.

fix(slider): Added touchevents and eventemitter to listen for value change

---

components/src/components/accordion/accordion.scss
components/src/components/radio-button/radio-button.scss

Removed use of get-colour function in component styling

fix: style in radiobtn and accordion after move

---

components/src/alpha/spinner/spinner.scss
components/src/components/modal/_modal-core.scss

**Describe pull-request** 
Moving theming rules to component folder 
Fixes: [AB#2221](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2221)

fix(spinner): move theming rules to component folder

---

.eslintrc.json

Disabled eslint prefer-default-export rule.

chore: disabled eslint prefer-default-export rule

---

components/src/alpha/slider-alpha/slider-alpha.scss

Slider alpha didn't work after style move
Check slider alpha in storybook

fix(slider-alpha): fix style after move

---

components/package-lock.json
components/package.json
components/src/components/banner/banner.stories.ts
components/src/components/my-component/my-component.tsx
components/src/utils/utils.spec.ts
components/src/utils/utils.ts

I suggest we merge this and use it in our migration PRs to make the code examples more readable and consistent!
Open storybook and look at the code of the banner story.
html-format that i suggested earlier had an issue with preserving redundant newlines.

docs: add util to format story html

---

components/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.tsx
components/src/components/tabs/inline-tabs/inline-tabs.tsx
components/src/components/tabs/navigation-tabs/navigation-tabs.tsx
sandbox/react/src/components/home/Home.js

Description says it all.
Open the react project in the sandbox. Reload the page and make sure the tabs are of equal width.

fix(tabs): Calculate tabwidth (and auto height) in componentDidRender()-method

---

components/package-lock.json
components/package.json

chore: release 42

---

components/package-lock.json
components/package.json
components/src/components/link/link-theme-vars.scss
components/src/components/link/link.scss
components/src/components/link/link.stories.ts
components/src/global/global.scss

Migrate link component
Fixes: [AB#2399](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2399)

feat(link): migrate link component

---

components/src/components.d.ts
components/src/components/accordion/accordion-item.tsx
components/src/components/accordion/accordion-theme-vars.scss
components/src/components/accordion/accordion.scss
components/src/components/accordion/accordion.spec.ts
components/src/components/accordion/accordion.stories.ts
components/src/components/accordion/accordion.tsx
components/src/components/accordion/readme.md
components/src/global/global.scss

Migrate accordion component
Fixes: [AB#2383](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2383)

feat(accordion): migrate accordion component

---

components/src/components/toggle/toggle-theme-vars.scss
components/src/components/toggle/toggle.scss
components/src/components/toggle/toggle.stories.ts
components/src/global/global.scss

Migrate toggle component.
Fixes: [AB#2391](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2391)

feat(toggle): migrate toggle component

---

components/src/components/message/message-theme-vars.scss
components/src/components/message/message.scss
components/src/components/message/message.stories.js
components/src/global/global.scss

Migrated message component. Includes the creation on theme-vars file and clean up of the story.
Fixes: [AB#2403](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2403)
2. Check in components -> message
3. Check that the design is aligned with the one in figma.
-
-

feat(message): migrate message component

---

components/src/components/message/message.stories.js

Added back theme to the controls
Fixes: -
2. Check in components -> message
3. Check that controls contains the theme radio buttons.
-
-

docs(message): added back theme to the controls

---

tegel/src/components/checkbox/checkbox.stories.ts

Removed Native from the components path in storybook
Fixes: -
2. Check in components
3. Check that the file path does not include Native
-
-

fix(checkbox): removed Native from the components path in storybook

---

tegel/.eslintrc.json
tegel/src/components/checkbox/checkbox.stories.ts

Clean up the story file of the checkbox
Adding this one to see if Netlify will kick in with preview deploy

fix: checkbox story cleanup + eslint rule for import resolution

---

tegel/package.json
tegel/src/components/popover-menu/documentation.txt
tegel/src/components/popover-menu/popover-menu-item.scss
tegel/src/components/popover-menu/popover-menu-theme-vars.scss
tegel/src/components/popover-menu/popover-menu.scss
tegel/src/components/popover-menu/popover-menu.stories.js
tegel/src/components/popover-menu/popover-menu.tsx
tegel/src/components/popover-menu/readme.md
tegel/src/global/global.scss

Migration of popover-menu component.
Fixes: [AB#2413](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2413)
2. Check in components -> popover-menu
3. Check that the design is aligned with the one in Figma. 
-
-

feat(popover-menu): migrate popover-menu component

---

tegel/src/components/textarea/readme.md
tegel/src/components/textarea/textarea-theme-vars.scss
tegel/src/components/textarea/textarea.scss
tegel/src/components/textarea/textarea.stories.js
tegel/src/components/textarea/textarea.tsx
tegel/src/components/textfield/readme.md
tegel/src/components/textfield/textfield-theme-vars.scss
tegel/src/components/textfield/textfield.scss
tegel/src/components/textfield/textfield.stories.js
tegel/src/components/textfield/textfield.tsx

Migration of textarea and textfield component
Fixes: [AB#2409](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2409) [AB#2410](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2410)
2. Check in components -> textarea/textfield
3. Check that the design is aligned with the one in Figma. 
-
-

feat(textarea/textfield): migrate textarea textfield component

---

tegel/package-lock.json
tegel/package.json

Adding more info to package.json file of Tegel
If you think of any other useful detail here, please let me know, I would gladly add it.

feat: adding more details to tegel package.json

---

tegel/src/components/textarea/textarea.stories.js
tegel/src/components/textfield/textfield.stories.js

Removed all but one story and added controls for the missing ones
Fixes: [AB#2459](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2459)
2. Check in components -> textfield/textarea
3. Test out the controls and check that they cover all scenarios. Also make sure the design is aligned with the one in Figma. 
-
-

fix(textarea/textfield): refine the number of stories

---

tegel/src/global/_utility-classes.scss
tegel/src/global/global.scss
tegel/src/mixins/_flex-center.scss
tegel/src/mixins/_focus-state.scss
tegel/src/mixins/_scrollbar.scss
tegel/src/mixins/_shake-animation.scss
tegel/src/mixins/mixins.scss
tegel/src/mixins/readme.md

adding utility classes and mixins to Tegel
Fixes: [AB#2407](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2407) [AB#2458](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2458)
1. To test utility classes, try to add one to the component or demo wrappers in Storybook
2. To test mixins, is tricky, but try to add one to some component when you branch out this code on your local.

fix: adding utility classes and mixins to Tegel

---

tegel/src/components/card/card.stories.ts

Improvement to the card component story. 
Fixes: -
2. Check in components -> card
3. Test out the controls and see that the design is aligned with the one in Figma.
-
-

fix(card): improve the story for the card component

---

tegel/src/components/theme/grid/grid.stories.js

Migration of the grid story
Fixes: [AB#2478](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2478)
2. Check in Foundations -> Grid
3. Check that the stories use and display the grid correctly.
-
-

feat(grid): migrate grid story

---

tegel/src/components/theme/spacing/spacing-element.stories.ts
tegel/src/components/theme/spacing/spacing-layout.stories.ts

Migrated the spacing story and separated the stories into different files.
Fixes: [AB#2479](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2479)
2. Check in Foundations -> Spacing
3. Check that the stories are understandable and reflect our spacing vars. 
-
-

feat(spacing): migrate spacing story

---

tegel/package.json
tegel/src/components/theme/typography/typography-body.stories.ts
tegel/src/components/theme/typography/typography-detail.stories.ts
tegel/src/components/theme/typography/typography-headline.stories.ts
tegel/src/components/theme/typography/typography-paragraph.stories.ts

Migration of the typography stories.
Fixes: [AB#2480](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2480)
2. Check in Foundations -> Typography
3. Check that the correct font styles are being applied. 
-
-

feat(typography): migrate typography stories

---

tegel/package.json

chore: enable 'npm run commit' from tegel directory

---

tegel/src/components/tooltip/readme.md
tegel/src/components/tooltip/tooltip-theme-vars.scss
tegel/src/components/tooltip/tooltip.scss
tegel/src/components/tooltip/tooltip.stories.js
tegel/src/components/tooltip/tooltip.tsx
tegel/src/global/global.scss

Migrating dropdown
Azure ticket [AB#2401](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2401)

feat(tooltips): migrating component

---

tegel/src/components/breadcrumb/breadcrumb-theme-vars.scss
tegel/src/components/breadcrumb/breadcrumb.scss
tegel/src/components/breadcrumb/breadcrumb.stories.ts
tegel/src/global/global.scss

Migation of breadcrumbs to tegel
Fixes: [AB#2415](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2415)
1. open storybook
2. look at breadcrumb and se if its migrated properly

feat(breadcrumb): migrate breadcrumb

---

tegel/tsconfig.json

Prevents editor linter from complaining about decorators in tegel folder

chore: fix ts linting issue

---

tegel/src/components/data-table/table-body-row/table-body-row.tsx
tegel/src/components/data-table/table-body/table-body.tsx
tegel/src/components/data-table/table-header-cell/table-header-cell.tsx
tegel/src/components/data-table/table-header/table-header.tsx
tegel/src/components/data-table/table/readme.md

Refactored how the top and subcomponents use enableMultiselect.
Fixes: [AB#2500](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2500)
2. Check in Components -> Data-table -> Multiselect
3. Check that the component works as intended both with and without multiselect.
-
-

fix(data-table): refactored how the top and subcomponents use enableMultiselect

---

tegel/src/components/data-table/native-table.stories.ts
tegel/src/components/data-table/table-component-basic.stories.ts
tegel/src/components/data-table/table-component-batch-actions.stories.ts
tegel/src/components/data-table/table-component-custom-width.stories.ts
tegel/src/components/data-table/table-component-event-listeners.stories.ts
tegel/src/components/data-table/table-component-expandable-rows.stories.ts
tegel/src/components/data-table/table-component-filtering.stories.ts
tegel/src/components/data-table/table-component-multiselect.stories.ts
tegel/src/components/data-table/table-component-pagination.stories.ts
tegel/src/components/data-table/table-component-sorting.stories.ts

Standardise the controls and default values for the data-table.
Fixes: [AB#2552](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2552) 
2. Check in Components -> Data-table
3. Check the default values are all correct.
-
-

 fix(data-table): standardise controls-values 

---

tegel/src/components/side-menu/readme.md
tegel/src/components/side-menu/side-menu-theme-vars.scss
tegel/src/components/side-menu/side-menu.scss
tegel/src/components/side-menu/side-menu.stories.ts
tegel/src/global/global.scss

Migrating side menu
Fixes: [AB#2415](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2415)
1. check out the storybook and see if the side-menu is migrated in accordance with the migration guidelines.

feat(side-menu) Migrating side menu

---

tegel/.storybook/manager-head.html

Adding Plausible tool for monitoring visitors activity.
I want to test this one as it seems that then we do not need cookie consent messages.

feat(storybook): adding Plausible

---

tegel/src/components/data-table/table-body-cell/table-body-cell.tsx
tegel/src/components/data-table/table-body-row-expandable/table-body-row-expandable.tsx
tegel/src/components/data-table/table-body-row/table-body-row.tsx
tegel/src/components/data-table/table-body/dummy-data.json
tegel/src/components/data-table/table-body/table-body.tsx
tegel/src/components/data-table/table-footer/readme.md
tegel/src/components/data-table/table-footer/table-footer.tsx
tegel/src/components/data-table/table-header-cell/table-header-cell.tsx
tegel/src/components/data-table/table-header/table-header.tsx
tegel/src/components/data-table/table-toolbar/table-toolbar.tsx
tegel/src/components/data-table/table/readme.md
tegel/src/components/data-table/table/table.tsx

This PR:
- Makes it so data table uses the tablePropsChangedEvent for communicating all changes to table props.
- Makes it so child components of data table reads table props on initial load.
- Reorders class member variables and methods for readability and consistency.
- Removed commented code
- Fixes eslint errors
Checkout the branch and test in storybook locally
Or
Look at netlify deploy preview

refactor(datatable): increase code style consistency

---

tegel/.storybook/manager-head.html

Test custom rules for Plausible

feat(storybook): test custom Plausible

---

tegel/.storybook/manager-head.html

feat(storybook): test custom Plausible with path & args

---

tegel/.storybook/manager-head.html

feat(storybook): test custom Plausible eventListener addon

---

tegel/src/components/side-menu/side-menu.stories.ts

Cleaned up the story and standardised the controls. Also exposed the javascript in storybook. 
Fixes: [AB#2553](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2553)
2. Check in Components -> Side menu
3. Test the controls and check that everything works as intended.
-
-

docs(side-menu): cleaned up the story and standardised the controls

---

tegel/.storybook/preview.js

This removes the alphabetic sorting of controls, so they are presented as intended.
Fixes: [AB#2679](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2679)
2. Check in the controls of any component.
3. Make sure they are ordered in the same way they are represented in the default export. 
-
-

docs(all): removes alphabetic sorting of controls.

---

components/src/components/banner/banner.scss
tegel/src/components/banner/banner.scss
tegel/src/components/banner/banner.stories.ts
tegel/src/stories/Migration/Migration.stories.mdx

Fixes: [AB#2605](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2605) #619

fix(banner): close icon misplaced/shrinking when lots of text

---

tegel/src/stories/Migration/Migration.stories.mdx

Wrapped element in quotations
Fixes: -
2. Check in Migration.md
-
-

docs(migration.md): fix migration.md

---

components/src/components/dropdown/dropdown.tsx

Label and position inside on sm dropdown fix
Fixes: -
-
-

fix(dropdown): label and position inside on sm dropdown fix

---

components/package-lock.json
components/package.json

chore(release: 4.10.2): bumped npm version

---

tegel/src/components/banner/banner.stories.ts

*Describe pull-request**  
Added default as default and cleaned up story.
Fixes: [AB#2660](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2660)
2. Check in Components -> Banner
3. Check that default is the default type on story
-
-

docs(banner): added default as default and cleaned up story

---

tegel/src/components/button/button-native.stories.ts
tegel/src/components/button/button-webcomponent.stories.ts

Hid the icon control if size is xs.
Fixes: -
2. Check in Components -> Button
3. Try adding an icon to xs button or switch size of icon button to xs.
-
-

fix(button): corrected the use of icons with xs button

---

tegel/src/components/accordion/accordion-item/accordion-item.tsx
tegel/src/components/accordion/accordion-item/readme.md
tegel/src/components/accordion/accordion.stories.ts
tegel/src/components/accordion/readme.md
theme/light/package-lock.json

added separate readme for accordion item
Fixes: [AB#2584](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2584)
1. go to accordion in storybook
2. check the notes tab and see if there are separate readmes for accordion and accordion item

fix(accordion): added separate readme for accordion item

---

tegel/src/components/header/header-all.stories.ts
tegel/src/components/header/header-inline.stories.ts
tegel/src/components/header/header-search.stories.ts
tegel/src/components/header/header-toolbar.stories.ts
tegel/src/stories/Migration/Migration.stories.mdx

BREAKING CHANGE: Changes all occurrences of p or div to span on header
Changed all occurrences of p or div to span on header and updated to migration.md.
Fixes: [AB#2684](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2684) [AB#2686](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2686)
2. Check in Components -> Header
3. Check the story and the example code.
-
-

fix(header): changed div/p as child of button to span

---

tegel/src/components/banner/banner.stories.ts

Removed camelCase from subHeader
Fixes: [AB#2663](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2663)
2. Check in Components -> Banner
3. Check that the subheader name is correct.
-
-

fix(banner):removed camelCase from subHeader

---

tegel/src/components/popover-canvas/popover-canvas.stories.ts
tegel/src/components/popover-menu/popover-menu-icons.stories.ts
tegel/src/components/popover-menu/popover-menu.stories.ts

Changed the position control from radio to select (dropdown).
Fixes: [AB#2732](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2732)
2. Check in Components -> Popover Menu/Canvas
3. Check that the controls for position still works as inteded.
-
-

fix(popover):changed radio to select for position

---

package-lock.json
package.json
tegel/.storybook/main.js
tegel/package-lock.json
tegel/package.json

Hides accessibility, darkmode, figma plugins outside of development environment.
A development environment is idenfitifed with environment variable STORYBOOK_ENV=development
Fixes: [AB#2727](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2727)

docs: hide SB dev addons outside of dev

---

tegel/src/components/block/block.stories.ts

Removed demo styling and cleaned up story.
Fixes: [AB#2668](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2668) [AB#2665](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2665)
2. Check in Components -> Block
3. Check the story.
-
-

fix(block): removed demo styling and cleaned up story

---

tegel/src/components/textarea/readme.md
tegel/src/components/textarea/textarea.tsx
tegel/src/components/textfield/readme.md
tegel/src/components/textfield/textfield.tsx

Changed default value to empty string.
Fixes: [AB#2745](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2745)
-
-

fix(textarea/textfield): changed default value from null to empty string

---

package.json
tegel/src/components/spinner/spinner.stories.ts

chore: remove dependency html-format

---

components/src/components/dropdown/dropdown.scss
components/src/components/dropdown/dropdown.tsx
tegel/src/components/dropdown/dropdown-select.scss
tegel/src/components/dropdown/dropdown.scss
tegel/src/components/dropdown/dropdown.tsx

Changed the bottom padding for the button if the label is inside, also refactored the positioning of the actual inside label. Fixes for both components and tegel.
***NOTE***
I don't know if this is something we want to address when we refactor this components instead of these fixes?
Fixes: [AB#2463](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2463) #550
2. Check in Components -> Dropdown
3. Check the placement of the inside label and bottom padding of the button when there is an inside label.
-
-

fix(dropdown): label placement and padding

---

tegel/.storybook/manager-head.html

Removing Google Analytics from Storybook
We will keep on using Plausible for analytics.

fix: removing Google Analytics from storybook

---

tegel/src/components/accordion/accordion.stories.ts
tegel/src/components/chips/chips.stories.ts
tegel/src/components/datetime/datetime.stories.ts
tegel/src/components/divider/divider.stories.ts
tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.ts
tegel/src/components/dropdown/dropdown-wc-default.stories.ts
tegel/src/components/dropdown/dropdown-wc-multiselect.stories.ts
tegel/src/components/header/header-all.stories.ts
tegel/src/components/header/header-default.stories.ts
tegel/src/components/header/header-inline.stories.ts
tegel/src/components/header/header-search.stories.ts
tegel/src/components/header/header-toolbar.stories.ts
tegel/src/components/icon/icon-font.stories.ts
tegel/src/components/icon/icon-web-component.stories.ts
tegel/src/components/message/message.stories.ts
tegel/src/components/modal/modal-native.stories.ts
tegel/src/components/popover-menu/popover-menu-icons.stories.ts
tegel/src/components/popover-menu/popover-menu.stories.ts
tegel/src/components/side-menu/side-menu.stories.ts
tegel/src/components/theme/colour/colour-scales.stories.ts
tegel/src/components/theme/grid/grid.stories.ts

added description to all controls in storybook
Fixes: [AB#2488](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2488)
1. go to storybook
2. go trough all components and check if there are descriptions on all controls

fix(tegel): added description to all controls

---

tegel/src/components/button/button-native.stories.ts
tegel/src/components/button/button-webcomponent.stories.ts
tegel/src/components/card/card.stories.ts
tegel/src/components/divider/divider.stories.ts
tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.ts
tegel/src/components/dropdown/dropdown-native.stories.ts
tegel/src/components/dropdown/dropdown-wc-default.stories.ts
tegel/src/components/dropdown/dropdown-wc-multiselect.stories.ts
tegel/src/components/header/header-all.stories.ts
tegel/src/components/header/header-default.stories.ts
tegel/src/components/header/header-inline.stories.ts
tegel/src/components/header/header-search.stories.ts
tegel/src/components/header/header-toolbar.stories.ts
tegel/src/components/modal/modal-native.stories.ts
tegel/src/components/popover-canvas/popover-canvas.stories.ts
tegel/src/components/popover-menu/popover-menu-icons.stories.ts
tegel/src/components/popover-menu/popover-menu.stories.ts
tegel/src/components/side-menu/side-menu.stories.ts
tegel/src/components/slider/slider.stories.ts
tegel/src/components/textarea/textarea.stories.ts
tegel/src/components/textfield/textfield.stories.ts
tegel/src/components/tooltip/tooltip.stories.ts

Added comments to demo wrappers in storybook
[AB#2680](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2680)
Check storybook, ex button

docs(): add comments to demo wrappers in storybook

---

tegel/src/components/button/button-native.stories.ts
tegel/src/components/button/button-webcomponent.stories.ts
tegel/src/components/chips/chips.stories.ts
tegel/src/components/message/message.stories.ts
tegel/src/components/modal/modal.scss
tegel/src/components/popover-menu/popover-menu-item.scss
tegel/src/components/stepper/stepper.scss
tegel/src/components/stepper/stepper.stories.ts
tegel/src/components/toast/toast.stories.ts

Changed "Webcomponent" to "Web Component" in affected components.
Fixes: [AB#2752](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2752)
**How to test**
1. Check Storybook

fix(): Change "Webcomponent" to "Web Component" in relevant components

---

tegel/package-lock.json
tegel/package.json

Just package version changes after the first beta release of Tegel.

chore: tegel 0.0.1-beta.0 release

---

tegel/src/stories/IntroductionTegel.stories.mdx

docs(welcome-page): removed placeholder text

---

tegel/package-lock.json
tegel/package.json
tegel/readme.md
tegel/stencil.config.ts
tegel/tsconfig.json

Set stencil -v to 2.20.0, bumped npm version to latest, ignoring stories files on build.
Fixes: [AB#2845](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2845)
Try running it locally and run a build. 
-
-

build(tegel): committing correct stencil -v, igoring stories on build

---

tegel/.storybook/preview.css
tegel/.storybook/preview.js
tegel/src/components/accordion/accordion.scss
tegel/src/components/dropdown/_dropdown-core.scss
tegel/src/components/dropdown/dropdown.scss
tegel/src/components/footer/footer.scss
tegel/src/components/header/header.scss
tegel/src/components/modal/modal.scss
tegel/src/components/popover-canvas/popover-canvas.scss
tegel/src/components/popover-menu/popover-menu.scss
tegel/src/components/slider/slider.scss
tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
tegel/src/components/tabs/navigation-tabs/navigation-tabs.scss
tegel/src/components/textarea/textarea.scss
tegel/src/components/tooltip/tooltip.scss
tegel/src/mixins/_z-index.scss

**Clean up z indexes**
Charlotte together with Johnny have come up with a z-index table with new values associated with each component. Let's try to implement that in our components and see if all behaves as expected, or if we need to make changes to this table.
Test that both in the sandbox and in the angular demo.
https://www.figma.com/file/P9o0JuuAcdYY52lUAz3nMK/Elevation-principles?node-id=2:2
Technical solution idea: https://www.smashingmagazine.com/2014/06/sassy-z-index-management-for-complex-layouts/
Fixes: [AB#2308](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2308)
Checkout the file changes, and please do a quick smoke test in the deploy preview below 🙏

feat z-index

---

tegel/src/components/accordion/accordion-theme-vars.scss

Accordion dark mode
[AB#2757](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2757)

fix(accordion): add dark mode variables

---

tegel/src/components/link/link-theme-vars.scss

Dark variables for link component
[AB#2931](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2931)

fix(link): add dark mode variables

---

tegel/src/components/chips/chips-theme-vars.scss
tegel/src/components/chips/chips.scss

Fixes: [AB#2924](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2924)

fix(chips): add dark mode variables

---

components/package-lock.json
components/package.json
components/src/components.d.ts
components/src/components/tabs/inline-tabs-fullbleed/readme.md
components/src/components/tabs/inline-tabs/readme.md

chore: release 47

---

tegel/package-lock.json
tegel/package.json

Release 0.0.1-beta.11
Fixes: -
-
-
-

feat(beta.11): bumped npm version for release 0.0.1-beta.11

---

tegel/src/components/accordion/accordion-item/accordion-item.scss
tegel/src/components/accordion/accordion-theme-vars.scss
tegel/src/components/accordion/accordion.scss
tegel/src/components/badge/badges.scss
tegel/src/components/banner/banner-theme-vars.scss
tegel/src/components/banner/banner.scss
tegel/src/components/card/card-theme-vars.scss
tegel/src/components/card/card.scss
tegel/src/components/checkbox/checkbox-theme-vars.scss
tegel/src/components/checkbox/checkbox.scss
tegel/src/components/chips/chips-theme-vars.scss
tegel/src/components/chips/chips.scss
tegel/src/components/message/message-theme-vars.scss
tegel/src/components/message/message.scss
tegel/src/components/radio-button/radio-button-theme-vars.scss
tegel/src/components/radio-button/radio-button.scss
tegel/src/components/stepper/stepper-theme-vars.scss
tegel/src/components/stepper/stepper.scss
tegel/src/components/toggle/toggle-theme-vars.scss
tegel/src/components/toggle/toggle.scss

Changed some already merged theme variables to be more consistent 
Fixes: [AB#2949](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2949)

fix(): changed variable names in various components for consistency

---

tegel/src/components/block/block-theme-vars.scss
tegel/src/components/block/block.scss

**Describe pull-request** 
Block dark mode 
[AB#2759](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2759)

fix(block): add dark mode variables

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yaml

Fixing issues made during renaming components to component-old in the bug report template. 
Due to rename, we got tegel-old and lost components package.
Just check if there is no more tegel-old or components old in template.

docs(bug-report): text corrections

---

tegel/src/components/datetime/datetime-theme-vars.scss
tegel/src/components/datetime/datetime.scss

Fixes: [AB#2926](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2926)

fix(datetime): add dark mode variables

---

tegel/src/components/footer/footer-theme-vars.scss
tegel/src/components/footer/footer.scss

Fixes: [AB#2929](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2929)

fix(footer): add dark mode variables

---

tegel/src/components/breadcrumb/breadcrumb-component.scss
tegel/src/components/breadcrumb/breadcrumb-component.stories.ts
tegel/src/components/breadcrumb/breadcrumb-item/breadcrumb-item.scss
tegel/src/components/breadcrumb/breadcrumb-item/breadcrumb-item.tsx
tegel/src/components/breadcrumb/breadcrumb-item/readme.md
tegel/src/components/breadcrumb/breadcrumb.stories.tsx
tegel/src/components/breadcrumb/breadcrumb.tsx
tegel/src/components/breadcrumb/readme.md

Web component version of the breadcrumb.
Fixes: [AB#2854](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2854)
2. Check in Components -> Breadcrumb -> WebComponent
-
-

feat(breadcrumb): webcomponent

---

tegel/src/components/datetime/datetime.stories.tsx

Added correct default values for stories, date -> Date, time -> Time
Fixes: [AB#3024](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3024)
2. Check in Components -> Datetime
3. Check the stories for date and time type.

fix(datetime): added correct type values for stories

---

tegel/src/components/popover-canvas/popover-canvas.stories.tsx
tegel/src/components/popover-menu/popover-menu-icons.stories.tsx
tegel/src/components/popover-menu/popover-menu.stories.tsx

- Adds button element for button that opens popover
- Removes redundant css
- Sets default canvasPosition to Bottom start, as Bottom doesnt work as intended

fix: popover storybook code example

---

tegel/src/components/modal/modal-theme-vars.scss
tegel/src/components/modal/modal.scss
tegel/src/components/modal/modal.tsx

Fixes: [AB#2932](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2932)

fix(modal): add dark mode variables

---

tegel/src/components/popover-canvas/popover-canvas.scss
tegel/src/components/popover-canvas/popover-canvas.stories.tsx
tegel/src/components/popover-canvas/popover-canvas.tsx
tegel/src/components/popover-menu/popover-menu.tsx

Fixes popover position of centered positions
Fixes: [AB#2848](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2848)

fix: popover position

---

tegel/src/components/popover-canvas/popover-canvas-theme-vars.scss

Removed mistake so light mode works correctly 
Fixes: [AB#2933](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2933)

Dark mode popover 2933

---

tegel/src/components/divider/divider-theme-vars.scss
tegel/src/components/divider/divider.scss
tegel/src/components/divider/divider.stories.tsx
tegel/src/stories/Migration/Migration.stories.mdx

Fixes: [AB#2927](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2927)#

fix(divider): add dark mode variables

---

tegel/src/components/textarea/textarea-theme-vars.scss
tegel/src/components/textarea/textarea.scss
tegel/src/components/textarea/textarea.stories.tsx
tegel/src/components/textarea/textarea.tsx

Fixes: [AB#2937](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2937)

fix(textarea): add dark mode variables

---

tegel/src/components/slider/slider-theme-vars.scss
tegel/src/components/slider/slider.scss
tegel/src/components/slider/slider.tsx

Fixes: [AB#2935](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2935)

fix(slider): add dark mode variables

---

tegel/src/components/card/card-theme-vars.scss
tegel/src/components/card/card.stories.tsx

Changed on-white, on-grey-50 etc to primary and secondary
Fixes: [AB#2970](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2950)

Card mode variant rename

---

tegel/src/components/message/message-theme-vars.scss
tegel/src/components/message/message.scss
tegel/src/components/message/message.stories.tsx

Renaming the mode variant names to primary/secondary
Fixes: [AB#3086](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3086)

Message rename mode variant

---

tegel/.storybook/preview.js

style(storybook): removed keyboard shortcuts

---

tegel/src/components/tabs/inline-tabs-default/inline-tab/inline-tab.scss
tegel/src/components/tabs/inline-tabs-default/inline-tab/inline-tab.tsx
tegel/src/components/tabs/inline-tabs-default/inline-tab/readme.md
tegel/src/components/tabs/inline-tabs-default/inline-tabs.stories.tsx
tegel/src/components/tabs/inline-tabs-default/inline-tabs.tsx
tegel/src/stories/Migration/Migration.stories.mdx

Created a child element for inline-tabs.
Fixes: [AB#2961](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2961)
2. Check in Components -> Inline-tabs
3. Check that it works as before, lol.

feat(inline tabs): child element

---

tegel/src/components/accordion/accordion-theme-vars.scss
tegel/src/components/accordion/accordion.stories.tsx
tegel/src/components/accordion/accordion.tsx
tegel/src/components/accordion/readme.md
tegel/src/components/popover-canvas/popover-canvas-theme-vars.scss

Updating mode variant naming
Fixes: [AB#2970](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2970)

Accordion mode variant rename

---

tegel/src/components/button/button-component.tsx
tegel/src/components/button/button-native.stories.tsx
tegel/src/components/button/button-theme-vars.scss
tegel/src/components/button/button-webcomponent.stories.tsx
tegel/src/components/button/button.scss
tegel/src/components/button/readme.md
tegel/src/components/card/card.stories.tsx
tegel/src/stories/Migration/Migration.stories.mdx

Mode variants for button. Only difference between variants is button background in disabled state for primary and danger.
Fixes: [AB#3114](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3114)

Button mode variant 

---

tegel/src/components/card/card.scss
tegel/src/components/card/card.stories.tsx

Changed to correct divider class in card component

fix(card): fix divider class

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR template.
Fixes: [AB#3161](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3161)
1. Create a PR and try it out.

chore(pull request): updated PR template

---

tegel/src/components/icon/readme.md
tegel/src/components/message/message.stories.tsx
tegel/src/components/message/readme.md
tegel/src/components/message/sdds-message.scss
tegel/src/components/message/sdds-message.stories.tsx
tegel/src/components/message/sdds-message.tsx

Web component version of the message component. Also renamed native story to Native.
Fixes: [AB#3159](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3159)
1. Go to story book link below
2. Check in Component -> Message -> Web Component
3. Check that styling and functionality is correct

feat(message): webcomponent

---

tegel/.storybook/preview.js

Changed the canvas background to white as default
Fixes: [AB#3140](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3140)

chore: change default light mode variant to white

---

tegel/src/components/block/block.stories.tsx
tegel/src/components/block/readme.md
tegel/src/components/block/sdds-block.scss
tegel/src/components/block/sdds-block.stories.tsx
tegel/src/components/block/sdds-block.tsx

Webcomponent version of Block. Also renamed the native story.
Fixes: [AB#3160](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3160)
2. Check in Components -> Block -> Webcomponent
3. Check that the styling is correct.

feat(block): webcomponent

---

tegel/package-lock.json
tegel/src/components/icon/readme.md
tegel/src/components/textarea/textarea.tsx
tegel/src/components/textfield/readme.md
tegel/src/components/textfield/textfield-theme-vars.scss
tegel/src/components/textfield/textfield.scss
tegel/src/components/textfield/textfield.stories.tsx
tegel/src/components/textfield/textfield.tsx

Changed mode variant class and added variables for dark mode
Fixes: [AB#3114](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3114)

Textfield mode variants

---

tegel/src/components/tabs/inline-tabs-default/inline-tabs-theme-vars.scss
tegel/src/components/tabs/inline-tabs-default/inline-tabs.scss
tegel/src/components/tabs/inline-tabs-default/inline-tabs.stories.tsx
tegel/src/components/tabs/inline-tabs-default/inline-tabs.tsx
tegel/src/components/tabs/inline-tabs-default/readme.md
tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed-theme-vars.scss
tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.stories.tsx
tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.tsx
tegel/src/components/tabs/inline-tabs-fullbleed/readme.md
tegel/src/components/tabs/navigation-tabs/navigation-tabs-theme-vars.scss
tegel/src/components/tabs/navigation-tabs/navigation-tabs.stories.tsx
tegel/src/components/tabs/navigation-tabs/navigation-tabs.tsx
tegel/src/components/tabs/navigation-tabs/readme.md

Mode variants for tabs. White background is primary and grey-50 secondary
Fixes: [AB#3117](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3117)

Tabs mode variants task 

---

tegel/src/components/icon/readme.md
tegel/src/components/toast/readme.md
tegel/src/components/toast/sdds-toast.scss
tegel/src/components/toast/sdds-toast.stories.tsx
tegel/src/components/toast/sdds-toast.tsx
tegel/src/components/toast/toast.scss
tegel/src/components/toast/toast.stories.tsx

Webcomponent version of toast. Also renamed native story.
Fixes: [AB#3166](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3166)
2. Check in Components -> Toast -> Toast
3. Check that the design is aligned with figma and try out the controls.

feat(toast): webcomponent

---

tegel/src/components/footer/footer-theme-vars.scss
tegel/src/components/footer/footer.scss
tegel/src/components/footer/footer.stories.tsx

Added mode variant for the top part in light mode
Fixes: [AB#3167](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3167)

feat(footer): add mode variant for light mode top part

---

tegel/.storybook/preview.js
tegel/src/components/datetime/datetime-theme-vars.scss
tegel/src/components/datetime/datetime.scss
tegel/src/components/datetime/datetime.stories.tsx
tegel/src/components/datetime/datetime.tsx
tegel/src/components/datetime/readme.md

New PR because
Fixes: [AB#3188](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3188)

Feat(datetime): mode variants task 3188

---

tegel/src/components/toast/readme.md
tegel/src/components/toast/sdds-toast.stories.tsx
tegel/src/components/toast/sdds-toast.tsx

Refactored event to conform with naming convention.
Fixes: [AB#3366](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3366)
2. Check in Components -> Toast -> Web Component
3. Check the event names in readme and console.log on close click.

fix(toast): refactor events

---

tegel/.storybook/main.js

Enabled dark mode in production.
Fixes: [AB#3352](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3352)
Needs to be double checked in production, can't be tested on preview.
1. Checkout branch
2. Change you env file to set environment to production.
3. Check that dark mode is still visible.

build(dark mode): enabled dark mode in production

---

tegel/src/components/card/readme.md
tegel/src/components/card/sdds-card.stories.tsx
tegel/src/components/card/sdds-card.tsx

Refactored event names to conform with naming convention.
Fixes: [AB#3368](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3368)
2. Check in Components -> Card -> Web Component
3. Check the readme 

feat(card): refactor events

---

tegel/.storybook/main.js

Double "import" of dark-mode plugin lead to build issues. This PR removes the unnecessary one.

build(addons): removed double dark mode addon

---

components/package-lock.json
components/package.json

Bumped NPM version to 4.10.6
Fixes: [AB#3354](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3354)

chore: release 51

---

readme.md

Updated to correct tegel URL in readme
No issue reported
1. Go to readme
2. Check in the tegel URL at the top of the document

Changed URL to tegel

---

tegel/src/components/block/sdds-block.tsx
tegel/src/components/datetime/datetime.tsx
tegel/src/components/tabs/inline-tabs-default/inline-tabs.stories.tsx

Some component still had null as valid input. Also fixed inline-tab sb.

fix: null not valid value for mode variant prop

---

tegel/src/components/radio-button/radio-button-component.scss
tegel/src/components/radio-button/radio-button-component.stories.tsx
tegel/src/components/radio-button/radio-button-theme-vars.scss
tegel/src/components/radio-button/radio-button.stories.tsx
tegel/src/components/radio-button/radio-button.tsx
tegel/src/components/radio-button/readme.md

Web component version of the radio button component. Also renamed native story to Native.
Fixes: [AB#3125](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3125)
1. Go to story book link below
2. Check in Component -> Radio Button-> Web Component
3. Check that styling and functionality is correct

feat(radio button): web component

---

tegel/src/components/checkbox/readme.md
tegel/src/components/checkbox/sdds-checkbox.stories.tsx
tegel/src/components/checkbox/sdds-checkbox.tsx

Fixes: [AB#3364](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3364)
2. Check in Components -> Checkbox -> Web Component
3. Check the readme for the event specification.
4. Check the console for events being emitted on story.

fix(checkbox): refactor event names

---

tegel/package-lock.json
tegel/package.json

Bumped npm version of Tegel package.
Fixes: [AB#3349](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3349)

build: Tegel release 51

---

tegel/tegel-release.sh

Created a small release script for tegel.
Fixes: -
Try using it next time we do a release of tegel.

build(release script): created a small release script for tegel

---

tegel/src/components/footer/footer-vars.scss
tegel/src/components/footer/footer.stories.tsx
tegel/src/components/footer/webcomponent/readme.md
tegel/src/components/footer/webcomponent/sdds-footer-link-group/readme.md
tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.scss
tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.tsx
tegel/src/components/footer/webcomponent/sdds-footer-link/readme.md
tegel/src/components/footer/webcomponent/sdds-footer-link/sdds-footer-link.scss
tegel/src/components/footer/webcomponent/sdds-footer-link/sdds-footer-link.tsx
tegel/src/components/footer/webcomponent/sdds-footer.scss
tegel/src/components/footer/webcomponent/sdds-footer.stories.tsx
tegel/src/components/footer/webcomponent/sdds-footer.tsx
tegel/src/components/icon/readme.md

Webcomponent version of the component. 
Fixes:[AB#3129](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/3129)
2. Check in Components -> Footer -> Web Component
3. Check out the API and check that the styling is correct.

feat(footer): webcomponent

---

tegel/src/components/card/sdds-card.scss

Make card 100% width.
Fixes: -

fix(sdds-card): width of card should always try to be 100%

---

tegel/readme.md
tegel/src/stories/Events/Events.stories.mdx

Updated the event docs with an explanation on how to do it in React.
Fixes: -
2. Check in Intro/Tegel - Events

docs(event): updated event docs

---

components/src/components/modal/modal.tsx
components/src/components/modal/readme.md
components/src/components/textarea/readme.md
components/src/components/textarea/textarea.tsx
components/src/components/textfield/readme.md
components/src/components/textfield/textfield.tsx

Updated the focus/blur/input/change event for the textfield/textarea. Added a sddsClose event for the modal.
Fixes: #767 #759
1. Check out the branch
2. Run npm run storybook for components
3. Check the readme

feat(events - textfield/textarea/modal): updated events

---

tegel/src/components/modal/readme.md

adds uncommitted readme for modal

fix(modal): readme for modal

---

tegel/src/components/divider/divider.spec.ts

Forgot to update spec to reflect the update to prop name. 
Fixes: #
Run spec locally, either with ```npm test``` to run all or unit tests, or target specfic test.

fix(divider): update spec to reflect prop name change

---

components/package-lock.json
components/package.json

Bumped npm version for release 53

chore: release 53

---

tegel/src/components/tabs/folder-tabs/folder-tabs-button/sdds-folder-tabs-button.tsx
tegel/src/components/tabs/folder-tabs/folder-tabs-link/sdds-folder-tabs-link.tsx
tegel/src/components/tabs/folder-tabs/folder-tabs.stories.tsx
tegel/src/components/tabs/inline-tabs/inline-tabs-button/sdds-inline-tabs-button.tsx
tegel/src/components/tabs/inline-tabs/inline-tabs-link/sdds-inline-tabs-link.tsx
tegel/src/components/tabs/inline-tabs/inline-tabs.stories.tsx
tegel/src/components/tabs/navigation-tabs/navigation-tabs-button/sdds-navigation-tabs-button.tsx
tegel/src/components/tabs/navigation-tabs/navigation-tabs-link/sdds-navigation-tabs-link.tsx
tegel/src/components/tabs/navigation-tabs/navigation-tabs.stories.tsx
tegel/src/stories/Migration/Migration.stories.mdx

Added a name to the default slot to make it handle dynamic data.
Fixes: -
2. Check in Components -> Tabs -> Folder/Inline/Navigation tabs
3. Check that everything is still working as expected..

fix(tabs): added a name to the default slot

---

tegel/src/components/checkbox/sdds-checkbox.stories.tsx
tegel/src/components/checkbox/sdds-checkbox.tsx

Replaced the default slot with a named slot. 
Fixes: -
2. Check in Components -> Checkbox
3. Check that everything still works as expected.

fix(checkbox): added a name to the default slot 

---

tegel/package.json

Release 0.0.51 of Tegel package.

chore: release 0.0.51

---

tegel/src/components/toggle/toggle-vars.scss

Changed toggle label from grey-900 to grey-958.

fix(toggle): correct label color in light mode

---

components/package-lock.json
components/package.json

Release of version 4.10.8 of @scania/components package

chore: release 4.10.8

---

tegel/src/components/card/sdds-card.tsx

Marked click event as non-cancelable.
Fixes: https://tegel.atlassian.net/browse/DTS-1089

fix(card): cancelable events

---

tegel/src/stories/Installation/Installation.stories.mdx

Added description on how to use Tegel components in a stencil.js project. 
Fixes: [DTS-1490](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=DTS-1490)
1. Go to Intro -> Tegel Beta Installation
2. Check in last section at the end and possibly try it out locally by creating a stencil.js project and installing Tegel. 
[DTS-1490]: https://tegel.atlassian.net/browse/DTS-1490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

docs(readme): added info about adding Tegel to stencil.js project

---

tegel/src/components/data-table/table-body/table-body.tsx
tegel/src/components/data-table/table.filtering.spec.tsx
tegel/src/components/data-table/table.spec.tsx

Added a "mock", created a crypto object on the globalThis to enable crypto to set a random ID in tests. Also since we are reassigning the value of bodyData to jsonDommyData if the users enabled this, we need to make the bodyData mutable.
Fixes: -
1. Check out branch.
3. Run npm run test
4. See the tests pass.

test(table): added a "mock" for crypto and made bodyData mutable

---

tegel/src/components/tabs/navigation-tabs/navigation-tabs.stories.tsx

Updated docs to have a anchor instead of a button in the navigation tabs.
Fixes: #
1. Check that everything is still OK.

docs(navigation-tabs): anchor on navigation tabs

---

tegel/package-lock.json
tegel/package.json

Release of @scania/tegel: 0.0.6

chore: tegel 0.0.6

---

tegel/stencil.config.ts
tegel/tsconfig.json

Added flag to not include sourcemaps in the prod build. Also removed a inclusion of jest types in our build.
Fixes:
https://tegel.atlassian.net/browse/DTS-1593
1. Check out the branch and build.
2. Check the .dist folder size.

build(config): removed sourcemaps and package.json from build

---

tegel/readme.md

Small updates to the tegel readme. Added table of content, tags and a status section that highlight that this package is in a pre-beta stage.
Fixes: 
1. Check it out here: https://github.com/scania-digital-design-system/sdds/tree/docs/update-tegel-readme/tegel

docs(readme): small updates to the tegel readme

---

tegel/package.json

Bumped our npm version to match the latest release.

build(npm version): bumped npm version to 0.0.7

---

components/src/components/checkbox/checkbox.scss
components/src/components/radio-button/radio-button.scss
tegel/src/components/checkbox/sdds-checkbox.scss
tegel/src/components/radio-button/radio-button-component.scss

…t in the label
Issue:
After:
Fixes: #DTS-1601, #DTS-1602
Issue found by Gökberk in support channel.

fix(checkbox,radio): fixed multiple lines of label text layout

---

components/package-lock.json
components/package.json

Release of @scani/component: 4.10.9

chore: components 4.10.9

---

tegel/src/stories/Migration/Migration.stories.mdx

Removes all native components in the migration docs and updated links.
Fixes: -
2. Check migration docs.

docs(migration docs): updated migration docs

---

components/src/components/stepper/stepper.stories.js
package.json

Fixes: https://tegel.atlassian.net/browse/DTS-1662

build(sdds): updated build scripts in package.json

---

theme/readme.md

Updated the readme for sdds/theme to only include current state.
Fixes: https://tegel.atlassian.net/browse/DTS-1718

docs(readme): updated readme for theme to only include current state

---

.github/ISSUE_TEMPLATE/BUG_REPORT.yaml
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.yaml
.github/ISSUE_TEMPLATE/REQUEST_HELP.yaml
.github/PULL_REQUEST_TEMPLATE.md
MIGRATION.md
components/readme.md
components/src/components/popover-canvas/documentation.txt
components/src/components/popover-canvas/popover-canvas.stories.js
components/src/components/popover-menu/documentation.txt
components/src/components/popover-menu/popover-menu.stories.js
sandbox/HTML/README.md
sandbox/angular/src/app/components/home/home.component.html
sandbox/angular/src/app/components/main/main.component.html
sandbox/angular/src/main.ts
sandbox/react/README.md
sandbox/react/src/components/home/Home.js
sandbox/react/src/index.js
sandbox/vue/README.md
sandbox/vue/src/components/Main.vue
theme/core/colour/README.md
theme/core/grid/README.md
theme/core/typography/README.md

Updated links pointing to digitaldesign.scania.com to tegel.scania.com
Fixes: https://tegel.atlassian.net/browse/DTS-1750
1. Check out branch
2. Search for digitaldesign in repo
3. Make sure all hits are only cdn links.

docs(web links): updated web links pointing to digitaldesign -> tegel

---

components/src/components/slider/slider.tsx

Fixes: #
1. Go to...
2. Check in...
3. Run ...

fix(slider): removing null initial value on boolean type

---

components/package.json
package-lock.json
package.json

Release 60

---

sandbox/react/package.json
sandbox/react/src/components/home/Home.js

Example in Reatc with Multiselect dropdown with preselected values

fix(sandbox-react): example with multiselect dropdown and preselected values

---

components/package-lock.json
components/package.json

Release of 4.10.13 components code

chore: release 4.10.13
